module Dodopayments
  module Models
    module Invoices
      type payment_retrieve_params =
        {  } & Dodopayments::Internal::Type::request_parameters

      class PaymentRetrieveParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        def initialize: (?request_options: Dodopayments::request_opts) -> void

        def to_hash: -> Dodopayments::Models::Invoices::payment_retrieve_params
      end
    end
  end
end
