configured_endpoints: 44
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-830ab144cfe8dad14cd5675173e036cd9683cb260786020aafdce6490851924f.yml
