configured_endpoints: 50
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-b7fbca15a61aece7c6807a5ef27eb80bc4d61abf636509e7fa10dfb04150913d.yml
openapi_spec_hash: 60c73621e45f1fb89edebc063d6e666f
config_hash: 1de70a388a640f9a3a055eaea8bddabd
