configured_endpoints: 57
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-269a0ca9c71ba7e54322c6101af341e507db3ec8dbd1a2289ded62be21a48e3c.yml
openapi_spec_hash: f3a6a43c54a4f6b92bc5d4f84db41efe
config_hash: 8bf855dbf3db83432149aeec3ebd1ea4
