module Dodopayments
  module Resources
    class Customers
      class CustomerPortal
        def create:
          (
            String customer_id,
            ?Dodopayments::Models::Customers::CustomerPortalCreateParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            String customer_id,
            send_email: bool?,
            request_options: Dodopayments::request_opts
          ) -> nil

        def initialize: (client: Dodopayments::Client) -> void
      end
    end
  end
end
