module Dodopayments
  module Resources
    class ProductCollections
      class Groups
        attr_reader items: Dodopayments::Resources::ProductCollections::Groups::Items

        def create: (
          String id,
          products: ::Array[Dodopayments::ProductCollections::GroupCreateParams::Product],
          ?group_name: String?,
          ?status: bool?,
          ?request_options: Dodopayments::request_opts
        ) -> Dodopayments::Models::ProductCollections::GroupCreateResponse

        def update: (
          String group_id,
          id: String,
          ?group_name: String?,
          ?product_order: ::Array[String]?,
          ?status: bool?,
          ?request_options: Dodopayments::request_opts
        ) -> nil

        def delete: (
          String group_id,
          id: String,
          ?request_options: Dodopayments::request_opts
        ) -> nil

        def initialize: (client: Dodopayments::Client) -> void
      end
    end
  end
end
