module Dodopayments
  module Models
    module Customers
      type customer_portal_create_params =
        { send_email: bool? } & Dodopayments::Internal::Type::request_parameters

      class CustomerPortalCreateParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        attr_accessor send_email: bool?

        def initialize: (
          ?send_email: bool?,
          ?request_options: Dodopayments::request_opts
        ) -> void

        def to_hash: -> {
          send_email: bool?,
          request_options: Dodopayments::RequestOptions
        }
      end
    end
  end
end
