module DodoPayments
  module Resources
    class Invoices
      class Payments
        def retrieve:
          (
            String payment_id,
            ?DodoPayments::Models::Invoices::PaymentRetrieveParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            String payment_id,
            request_options: DodoPayments::request_opts
          ) -> nil

        def initialize: (client: DodoPayments::Client) -> void
      end
    end
  end
end
