module DodoPayments
  module Resources
    class LicenseKeyInstances
      def retrieve:
        (
          String id,
          ?DodoPayments::Models::LicenseKeyInstanceRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::LicenseKeyInstance
        | (
          String id,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::LicenseKeyInstance

      def update:
        (
          String id,
          DodoPayments::Models::LicenseKeyInstanceUpdateParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::LicenseKeyInstance
        | (
          String id,
          name: String,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::LicenseKeyInstance

      def list:
        (
          ?DodoPayments::Models::LicenseKeyInstanceListParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::license_key_instance_list_response
        | (
          license_key_id: String?,
          page_number: Integer?,
          page_size: Integer?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::license_key_instance_list_response

      def initialize: (client: DodoPayments::Client) -> void
    end
  end
end
