module DodoPayments
  module Resources
    class LicenseKeys
      def retrieve:
        (
          String id,
          ?DodoPayments::Models::LicenseKeyRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::LicenseKey
        | (
          String id,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::LicenseKey

      def update:
        (
          String id,
          ?DodoPayments::Models::LicenseKeyUpdateParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::LicenseKey
        | (
          String id,
          activations_limit: Integer?,
          disabled: bool?,
          expires_at: Time?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::LicenseKey

      def list:
        (
          ?DodoPayments::Models::LicenseKeyListParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::license_key_list_response
        | (
          customer_id: String?,
          page_number: Integer?,
          page_size: Integer?,
          product_id: String?,
          status: DodoPayments::Models::LicenseKeyListParams::status?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::license_key_list_response

      def initialize: (client: DodoPayments::Client) -> void
    end
  end
end
