module DodoPayments
  module Resources
    class Payouts
      def list:
        (
          ?DodoPayments::Models::PayoutListParams | ::Hash[Symbol, top] params
        ) -> DodoPayments::DefaultPageNumberPagination[DodoPayments::Models::PayoutListResponse]
        | (
          page_number: Integer?,
          page_size: Integer?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::DefaultPageNumberPagination[DodoPayments::Models::PayoutListResponse]

      def initialize: (client: DodoPayments::Client) -> void
    end
  end
end
