module DodoPayments
  module Resources
    class Products
      attr_reader images: DodoPayments::Resources::Products::Images

      def create:
        (
          DodoPayments::Models::ProductCreateParams | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::Product
        | (
          price: DodoPayments::Models::ProductCreateParams::price,
          tax_category: DodoPayments::Models::ProductCreateParams::tax_category,
          description: String?,
          license_key_activation_message: String?,
          license_key_activations_limit: Integer?,
          license_key_duration: DodoPayments::Models::ProductCreateParams::LicenseKeyDuration?,
          license_key_enabled: bool?,
          name: String?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::Product

      def retrieve:
        (
          String id,
          ?DodoPayments::Models::ProductRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::Product
        | (
          String id,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::Product

      def update:
        (
          String id,
          ?DodoPayments::Models::ProductUpdateParams
          | ::Hash[Symbol, top] params
        ) -> nil
        | (
          String id,
          description: String?,
          image_id: String?,
          license_key_activation_message: String?,
          license_key_activations_limit: Integer?,
          license_key_duration: DodoPayments::Models::ProductUpdateParams::LicenseKeyDuration?,
          license_key_enabled: bool?,
          name: String?,
          price: DodoPayments::Models::ProductUpdateParams::price?,
          tax_category: DodoPayments::Models::ProductUpdateParams::tax_category?,
          request_options: DodoPayments::request_opts
        ) -> nil

      def list:
        (
          ?DodoPayments::Models::ProductListParams | ::Hash[Symbol, top] params
        ) -> DodoPayments::DefaultPageNumberPagination[DodoPayments::Models::ProductListResponse]
        | (
          archived: bool,
          page_number: Integer?,
          page_size: Integer?,
          recurring: bool?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::DefaultPageNumberPagination[DodoPayments::Models::ProductListResponse]

      def delete:
        (
          String id,
          ?DodoPayments::Models::ProductDeleteParams
          | ::Hash[Symbol, top] params
        ) -> nil
        | (String id, request_options: DodoPayments::request_opts) -> nil

      def unarchive:
        (
          String id,
          ?DodoPayments::Models::ProductUnarchiveParams
          | ::Hash[Symbol, top] params
        ) -> nil
        | (String id, request_options: DodoPayments::request_opts) -> nil

      def initialize: (client: DodoPayments::Client) -> void
    end
  end
end
