module DodoPayments
  module Resources
    class Subscriptions
      def create:
        (
          DodoPayments::Models::SubscriptionCreateParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::SubscriptionCreateResponse
        | (
          billing: DodoPayments::Models::SubscriptionCreateParams::Billing,
          customer: DodoPayments::Models::SubscriptionCreateParams::customer,
          product_id: String,
          quantity: Integer,
          discount_code: String?,
          metadata: ::Hash[Symbol, String],
          payment_link: bool?,
          return_url: String?,
          tax_id: String?,
          trial_period_days: Integer?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::SubscriptionCreateResponse

      def retrieve:
        (
          String subscription_id,
          ?DodoPayments::Models::SubscriptionRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::Subscription
        | (
          String subscription_id,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::Subscription

      def update:
        (
          String subscription_id,
          ?DodoPayments::Models::SubscriptionUpdateParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::Models::Subscription
        | (
          String subscription_id,
          metadata: ::Hash[Symbol, String]?,
          status: DodoPayments::Models::SubscriptionUpdateParams::status?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::Models::Subscription

      def list:
        (
          ?DodoPayments::Models::SubscriptionListParams
          | ::Hash[Symbol, top] params
        ) -> DodoPayments::DefaultPageNumberPagination[DodoPayments::Models::Subscription]
        | (
          created_at_gte: Time?,
          created_at_lte: Time?,
          customer_id: String?,
          page_number: Integer?,
          page_size: Integer?,
          status: DodoPayments::Models::SubscriptionListParams::status?,
          request_options: DodoPayments::request_opts
        ) -> DodoPayments::DefaultPageNumberPagination[DodoPayments::Models::Subscription]

      def initialize: (client: DodoPayments::Client) -> void
    end
  end
end
