module Dodopayments
  module Models
    module Webhooks
      type header_retrieve_params =
        { webhook_id: String }
        & Dodopayments::Internal::Type::request_parameters

      class HeaderRetrieveParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        attr_accessor webhook_id: String

        def initialize: (
          webhook_id: String,
          ?request_options: Dodopayments::request_opts
        ) -> void

        def to_hash: -> {
          webhook_id: String,
          request_options: Dodopayments::RequestOptions
        }
      end
    end
  end
end
