module DodoPayments
  module Models
    module Misc
      type supported_country_list_response =
        ::Array[DodoPayments::Models::Misc::country_code]

      SupportedCountryListResponse: supported_country_list_response
    end
  end
end
