module DodoPayments
  module Models
    type customer_portal_session = { link: String }

    class CustomerPortalSession < DodoPayments::BaseModel
      attr_accessor link: String

      def initialize:
        (link: String) -> void
        | (
          ?DodoPayments::Models::customer_portal_session
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::customer_portal_session
    end
  end
end
