module DodoPayments
  module Models
    type customer_create_params =
      { email: String, name: String, phone_number: String? }
      & DodoPayments::request_parameters

    class CustomerCreateParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor email: String

      attr_accessor name: String

      attr_accessor phone_number: String?

      def initialize:
        (
          email: String,
          name: String,
          phone_number: String?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::customer_create_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::customer_create_params
    end
  end
end
