module DodoPayments
  module Models
    type dispute_list_params =
      {
        created_at_gte: Time?,
        created_at_lte: Time?,
        customer_id: String?,
        dispute_stage: DodoPayments::Models::DisputeListParams::dispute_stage?,
        dispute_status: DodoPayments::Models::DisputeListParams::dispute_status?,
        page_number: Integer?,
        page_size: Integer?
      }
      & DodoPayments::request_parameters

    class DisputeListParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor created_at_gte: Time?

      attr_accessor created_at_lte: Time?

      attr_accessor customer_id: String?

      attr_accessor dispute_stage: DodoPayments::Models::DisputeListParams::dispute_stage?

      attr_accessor dispute_status: DodoPayments::Models::DisputeListParams::dispute_status?

      attr_accessor page_number: Integer?

      attr_accessor page_size: Integer?

      def initialize:
        (
          created_at_gte: Time?,
          created_at_lte: Time?,
          customer_id: String?,
          dispute_stage: DodoPayments::Models::DisputeListParams::dispute_stage?,
          dispute_status: DodoPayments::Models::DisputeListParams::dispute_status?,
          page_number: Integer?,
          page_size: Integer?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::dispute_list_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::dispute_list_params

      type dispute_stage = :pre_dispute | :dispute | :pre_arbitration

      class DisputeStage < DodoPayments::Enum
        PRE_DISPUTE: :pre_dispute
        DISPUTE: :dispute
        PRE_ARBITRATION: :pre_arbitration

        def self.values: -> ::Array[DodoPayments::Models::DisputeListParams::dispute_stage]
      end

      type dispute_status =
        :dispute_opened
        | :dispute_expired
        | :dispute_accepted
        | :dispute_cancelled
        | :dispute_challenged
        | :dispute_won
        | :dispute_lost

      class DisputeStatus < DodoPayments::Enum
        DISPUTE_OPENED: :dispute_opened
        DISPUTE_EXPIRED: :dispute_expired
        DISPUTE_ACCEPTED: :dispute_accepted
        DISPUTE_CANCELLED: :dispute_cancelled
        DISPUTE_CHALLENGED: :dispute_challenged
        DISPUTE_WON: :dispute_won
        DISPUTE_LOST: :dispute_lost

        def self.values: -> ::Array[DodoPayments::Models::DisputeListParams::dispute_status]
      end
    end
  end
end
