module DodoPayments
  module Models
    type license_validate_params =
      { license_key: String, license_key_instance_id: String? }
      & DodoPayments::request_parameters

    class LicenseValidateParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor license_key: String

      attr_accessor license_key_instance_id: String?

      def initialize:
        (
          license_key: String,
          license_key_instance_id: String?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::license_validate_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::license_validate_params
    end
  end
end
