module DodoPayments
  module Models
    type license_activate_params =
      { license_key: String, name: String } & DodoPayments::request_parameters

    class LicenseActivateParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor license_key: String

      attr_accessor name: String

      def initialize:
        (
          license_key: String,
          name: String,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::license_activate_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::license_activate_params
    end
  end
end
