module DodoPayments
  module Models
    type license_key_instance_list_response_item =
      { items: ::Array[DodoPayments::Models::LicenseKeyInstance] }

    class LicenseKeyInstanceListResponseItem < DodoPayments::BaseModel
      attr_accessor items: ::Array[DodoPayments::Models::LicenseKeyInstance]

      def initialize:
        (items: ::Array[DodoPayments::Models::LicenseKeyInstance]) -> void
        | (
          ?DodoPayments::Models::license_key_instance_list_response_item
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::license_key_instance_list_response_item
    end

    type license_key_instance_list_response =
      ::Array[DodoPayments::Models::LicenseKeyInstanceListResponseItem]

    LicenseKeyInstanceListResponse: license_key_instance_list_response
  end
end
