module DodoPayments
  module Models
    type license_key_update_params =
      { activations_limit: Integer?, disabled: bool?, expires_at: Time? }
      & DodoPayments::request_parameters

    class LicenseKeyUpdateParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor activations_limit: Integer?

      attr_accessor disabled: bool?

      attr_accessor expires_at: Time?

      def initialize:
        (
          activations_limit: Integer?,
          disabled: bool?,
          expires_at: Time?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::license_key_update_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::license_key_update_params
    end
  end
end
