module DodoPayments
  module Models
    type payment_create_response =
      {
        client_secret: String,
        customer: DodoPayments::Models::PaymentCreateResponse::Customer,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        discount_id: String?,
        payment_link: String?,
        product_cart: ::Array[DodoPayments::Models::PaymentCreateResponse::ProductCart]?
      }

    class PaymentCreateResponse < DodoPayments::BaseModel
      attr_accessor client_secret: String

      attr_accessor customer: DodoPayments::Models::PaymentCreateResponse::Customer

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor payment_id: String

      attr_accessor total_amount: Integer

      attr_accessor discount_id: String?

      attr_accessor payment_link: String?

      attr_accessor product_cart: ::Array[DodoPayments::Models::PaymentCreateResponse::ProductCart]?

      def initialize:
        (
          client_secret: String,
          customer: DodoPayments::Models::PaymentCreateResponse::Customer,
          metadata: ::Hash[Symbol, String],
          payment_id: String,
          total_amount: Integer,
          discount_id: String?,
          payment_link: String?,
          product_cart: ::Array[DodoPayments::Models::PaymentCreateResponse::ProductCart]?
        ) -> void
        | (
          ?DodoPayments::Models::payment_create_response
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::payment_create_response

      type customer = { customer_id: String, email: String, name: String }

      class Customer < DodoPayments::BaseModel
        attr_accessor customer_id: String

        attr_accessor email: String

        attr_accessor name: String

        def initialize:
          (customer_id: String, email: String, name: String) -> void
          | (
            ?DodoPayments::Models::PaymentCreateResponse::customer
            | DodoPayments::BaseModel data
          ) -> void

        def to_hash: -> DodoPayments::Models::PaymentCreateResponse::customer
      end

      type product_cart =
        { product_id: String, quantity: Integer, amount: Integer? }

      class ProductCart < DodoPayments::BaseModel
        attr_accessor product_id: String

        attr_accessor quantity: Integer

        attr_accessor amount: Integer?

        def initialize:
          (product_id: String, quantity: Integer, amount: Integer?) -> void
          | (
            ?DodoPayments::Models::PaymentCreateResponse::product_cart
            | DodoPayments::BaseModel data
          ) -> void

        def to_hash: -> DodoPayments::Models::PaymentCreateResponse::product_cart
      end
    end
  end
end
