module DodoPayments
  module Models
    type payout_list_params =
      { page_number: Integer?, page_size: Integer? }
      & DodoPayments::request_parameters

    class PayoutListParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor page_number: Integer?

      attr_accessor page_size: Integer?

      def initialize:
        (
          page_number: Integer?,
          page_size: Integer?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::payout_list_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::payout_list_params
    end
  end
end
