module DodoPayments
  module Models
    type refund_create_params =
      { payment_id: String, amount: Integer?, reason: String? }
      & DodoPayments::request_parameters

    class RefundCreateParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor payment_id: String

      attr_accessor amount: Integer?

      attr_accessor reason: String?

      def initialize:
        (
          payment_id: String,
          amount: Integer?,
          reason: String?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::refund_create_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::refund_create_params
    end
  end
end
