module DodoPayments
  module Models
    type refund_list_params =
      {
        created_at_gte: Time?,
        created_at_lte: Time?,
        customer_id: String?,
        page_number: Integer?,
        page_size: Integer?,
        status: DodoPayments::Models::RefundListParams::status?
      }
      & DodoPayments::request_parameters

    class RefundListParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor created_at_gte: Time?

      attr_accessor created_at_lte: Time?

      attr_accessor customer_id: String?

      attr_accessor page_number: Integer?

      attr_accessor page_size: Integer?

      attr_accessor status: DodoPayments::Models::RefundListParams::status?

      def initialize:
        (
          created_at_gte: Time?,
          created_at_lte: Time?,
          customer_id: String?,
          page_number: Integer?,
          page_size: Integer?,
          status: DodoPayments::Models::RefundListParams::status?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::refund_list_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::refund_list_params

      type status = :succeeded | :failed | :pending | :review

      class Status < DodoPayments::Enum
        SUCCEEDED: :succeeded
        FAILED: :failed
        PENDING: :pending
        REVIEW: :review

        def self.values: -> ::Array[DodoPayments::Models::RefundListParams::status]
      end
    end
  end
end
