module DodoPayments
  module Models
    type webhook_event_list_params =
      {
        created_at_gte: Time?,
        created_at_lte: Time?,
        limit: Integer?,
        object_id_: String?,
        page_number: Integer?,
        page_size: Integer?
      }
      & DodoPayments::request_parameters

    class WebhookEventListParams < DodoPayments::BaseModel
      extend DodoPayments::RequestParameters::Converter
      include DodoPayments::RequestParameters

      attr_accessor created_at_gte: Time?

      attr_accessor created_at_lte: Time?

      attr_accessor limit: Integer?

      attr_accessor object_id_: String?

      attr_accessor page_number: Integer?

      attr_accessor page_size: Integer?

      def initialize:
        (
          created_at_gte: Time?,
          created_at_lte: Time?,
          limit: Integer?,
          object_id_: String?,
          page_number: Integer?,
          page_size: Integer?,
          request_options: DodoPayments::request_opts
        ) -> void
        | (
          ?DodoPayments::Models::webhook_event_list_params
          | DodoPayments::BaseModel data
        ) -> void

      def to_hash: -> DodoPayments::Models::webhook_event_list_params
    end
  end
end
