module DodoPayments
  module Models
    module Products
      type image_update_response = { url: String, image_id: String? }

      class ImageUpdateResponse < DodoPayments::BaseModel
        attr_accessor url: String

        attr_accessor image_id: String?

        def initialize:
          (url: String, image_id: String?) -> void
          | (
            ?DodoPayments::Models::Products::image_update_response
            | DodoPayments::BaseModel data
          ) -> void

        def to_hash: -> DodoPayments::Models::Products::image_update_response
      end
    end
  end
end
