module DodoPayments
  module Models
    module Products
      type image_update_params =
        { force_update: bool? } & DodoPayments::request_parameters

      class ImageUpdateParams < DodoPayments::BaseModel
        extend DodoPayments::RequestParameters::Converter
        include DodoPayments::RequestParameters

        attr_accessor force_update: bool?

        def initialize:
          (
            force_update: bool?,
            request_options: DodoPayments::request_opts
          ) -> void
          | (
            ?DodoPayments::Models::Products::image_update_params
            | DodoPayments::BaseModel data
          ) -> void

        def to_hash: -> DodoPayments::Models::Products::image_update_params
      end
    end
  end
end
