module DodoPayments
  module Resources
    class Customers
      class CustomerPortal
        attr_reader session: DodoPayments::Resources::Customers::CustomerPortal::Session

        def initialize: (client: DodoPayments::Client) -> void
      end
    end
  end
end
