module Dodopayments
  module Models
    module Products
      type localized_price_archive_params =
        { product_id: String, id: String }
        & Dodopayments::Internal::Type::request_parameters

      class LocalizedPriceArchiveParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        attr_accessor product_id: String

        attr_accessor id: String

        def initialize: (
          product_id: String,
          id: String,
          ?request_options: Dodopayments::request_opts
        ) -> void

        def to_hash: -> {
          product_id: String,
          id: String,
          request_options: Dodopayments::RequestOptions
        }
      end
    end
  end
end
