module Dodopayments
  module Models
    module ProductCollections
      type group_delete_params =
        { id: String, group_id: String }
        & Dodopayments::Internal::Type::request_parameters

      class GroupDeleteParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor group_id: String

        def initialize: (
          id: String,
          group_id: String,
          ?request_options: Dodopayments::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          group_id: String,
          request_options: Dodopayments::RequestOptions
        }
      end
    end
  end
end
