module Dodopayments
  module Models
    module Blocklist
      type customer_delete_params =
        { entry_id: String } & Dodopayments::Internal::Type::request_parameters

      class CustomerDeleteParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        attr_accessor entry_id: String

        def initialize: (
          entry_id: String,
          ?request_options: Dodopayments::request_opts
        ) -> void

        def to_hash: -> {
          entry_id: String,
          request_options: Dodopayments::RequestOptions
        }
      end
    end
  end
end
