module Dodopayments
  module Models
    type addon_create_params =
      {
        currency: Dodopayments::Models::currency,
        name: String,
        price: Integer,
        tax_category: Dodopayments::Models::tax_category,
        description: String?
      }
      & Dodopayments::Internal::Type::request_parameters

    class AddonCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor currency: Dodopayments::Models::currency

      attr_accessor name: String

      attr_accessor price: Integer

      attr_accessor tax_category: Dodopayments::Models::tax_category

      attr_accessor description: String?

      def initialize: (
        currency: Dodopayments::Models::currency,
        name: String,
        price: Integer,
        tax_category: Dodopayments::Models::tax_category,
        ?description: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void
    end
  end
end
