module Dodopayments
  module Models
    type addon_update_images_response = { image_id: String, url: String }

    class AddonUpdateImagesResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor image_id: String

      attr_accessor url: String

      def initialize: (image_id: String, url: String) -> void
    end
  end
end
