module Dodopayments
  module Models
    type attach_addon = { addon_id: String, quantity: Integer }

    class AttachAddon < Dodopayments::Internal::Type::BaseModel
      attr_accessor addon_id: String

      attr_accessor quantity: Integer

      def initialize: (addon_id: String, quantity: Integer) -> void

      def to_hash: -> { addon_id: String, quantity: Integer }
    end
  end
end
