module Dodopayments
  module Models
    type attach_existing_customer = { customer_id: String }

    class AttachExistingCustomer < Dodopayments::Internal::Type::BaseModel
      attr_accessor customer_id: String

      def initialize: (customer_id: String) -> void

      def to_hash: -> { customer_id: String }
    end
  end
end
