module Dodopayments
  module Models
    type brand_archive_params =
      { id: String, move_products_to: String? }
      & Dodopayments::Internal::Type::request_parameters

    class BrandArchiveParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor move_products_to: String?

      def initialize: (
        id: String,
        ?move_products_to: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        move_products_to: String?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
