module Dodopayments
  module Models
    type checkout_session_preview_params =
      {  } & Dodopayments::Internal::Type::request_parameters

    class CheckoutSessionPreviewParams < Dodopayments::Models::CheckoutSessionRequest
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> { request_options: Dodopayments::RequestOptions }
    end
  end
end
