module Dodopayments
  module Models
    type checkout_session_response =
      { checkout_url: String, session_id: String }

    class CheckoutSessionResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor checkout_url: String

      attr_accessor session_id: String

      def initialize: (checkout_url: String, session_id: String) -> void

      def to_hash: -> { checkout_url: String, session_id: String }
    end
  end
end
