module Dodopayments
  module Models
    type checkout_session_response =
      { session_id: String, checkout_url: String? }

    class CheckoutSessionResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor session_id: String

      attr_accessor checkout_url: String?

      def initialize: (session_id: String, ?checkout_url: String?) -> void

      def to_hash: -> { session_id: String, checkout_url: String? }
    end
  end
end
