module Dodopayments
  module Models
    type checkout_session_request =
      {
        product_cart: ::Array[Dodopayments::ProductItemReq],
        allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        billing_address: Dodopayments::CheckoutSessionBillingAddress?,
        billing_currency: Dodopayments::Models::currency?,
        confirm: bool,
        custom_fields: ::Array[Dodopayments::CustomField]?,
        customer: Dodopayments::Models::customer_request?,
        customization: Dodopayments::CheckoutSessionCustomization,
        discount_code: String?,
        feature_flags: Dodopayments::CheckoutSessionFlags,
        :force_3ds => bool?,
        metadata: ::Hash[Symbol, String]?,
        minimal_address: bool,
        payment_method_id: String?,
        product_collection_id: String?,
        return_url: String?,
        short_link: bool,
        show_saved_payment_methods: bool,
        subscription_data: Dodopayments::SubscriptionData?
      }

    class CheckoutSessionRequest < Dodopayments::Internal::Type::BaseModel
      attr_accessor product_cart: ::Array[Dodopayments::ProductItemReq]

      attr_accessor allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?

      attr_accessor billing_address: Dodopayments::CheckoutSessionBillingAddress?

      attr_accessor billing_currency: Dodopayments::Models::currency?

      attr_reader confirm: bool?

      def confirm=: (bool) -> bool

      attr_accessor custom_fields: ::Array[Dodopayments::CustomField]?

      attr_accessor customer: Dodopayments::Models::customer_request?

      attr_reader customization: Dodopayments::CheckoutSessionCustomization?

      def customization=: (
        Dodopayments::CheckoutSessionCustomization
      ) -> Dodopayments::CheckoutSessionCustomization

      attr_accessor discount_code: String?

      attr_reader feature_flags: Dodopayments::CheckoutSessionFlags?

      def feature_flags=: (
        Dodopayments::CheckoutSessionFlags
      ) -> Dodopayments::CheckoutSessionFlags

      attr_accessor force_3ds: bool?

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_reader minimal_address: bool?

      def minimal_address=: (bool) -> bool

      attr_accessor payment_method_id: String?

      attr_accessor product_collection_id: String?

      attr_accessor return_url: String?

      attr_reader short_link: bool?

      def short_link=: (bool) -> bool

      attr_reader show_saved_payment_methods: bool?

      def show_saved_payment_methods=: (bool) -> bool

      attr_accessor subscription_data: Dodopayments::SubscriptionData?

      def initialize: (
        product_cart: ::Array[Dodopayments::ProductItemReq],
        ?allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        ?billing_address: Dodopayments::CheckoutSessionBillingAddress?,
        ?billing_currency: Dodopayments::Models::currency?,
        ?confirm: bool,
        ?custom_fields: ::Array[Dodopayments::CustomField]?,
        ?customer: Dodopayments::Models::customer_request?,
        ?customization: Dodopayments::CheckoutSessionCustomization,
        ?discount_code: String?,
        ?feature_flags: Dodopayments::CheckoutSessionFlags,
        ?force_3ds: bool?,
        ?metadata: ::Hash[Symbol, String]?,
        ?minimal_address: bool,
        ?payment_method_id: String?,
        ?product_collection_id: String?,
        ?return_url: String?,
        ?short_link: bool,
        ?show_saved_payment_methods: bool,
        ?subscription_data: Dodopayments::SubscriptionData?
      ) -> void

      def to_hash: -> {
        product_cart: ::Array[Dodopayments::ProductItemReq],
        allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        billing_address: Dodopayments::CheckoutSessionBillingAddress?,
        billing_currency: Dodopayments::Models::currency?,
        confirm: bool,
        custom_fields: ::Array[Dodopayments::CustomField]?,
        customer: Dodopayments::Models::customer_request?,
        customization: Dodopayments::CheckoutSessionCustomization,
        discount_code: String?,
        feature_flags: Dodopayments::CheckoutSessionFlags,
        :force_3ds => bool?,
        metadata: ::Hash[Symbol, String]?,
        minimal_address: bool,
        payment_method_id: String?,
        product_collection_id: String?,
        return_url: String?,
        short_link: bool,
        show_saved_payment_methods: bool,
        subscription_data: Dodopayments::SubscriptionData?
      }
    end
  end
end
