module Dodopayments
  module Models
    type create_new_customer =
      {
        email: String,
        name: String,
        create_new_customer: bool,
        phone_number: String?
      }

    class CreateNewCustomer < Dodopayments::Internal::Type::BaseModel
      attr_accessor email: String

      attr_accessor name: String

      attr_reader create_new_customer: bool?

      def create_new_customer=: (bool) -> bool

      attr_accessor phone_number: String?

      def initialize: (
        email: String,
        name: String,
        ?create_new_customer: bool,
        ?phone_number: String?
      ) -> void

      def to_hash: -> {
        email: String,
        name: String,
        create_new_customer: bool,
        phone_number: String?
      }
    end
  end
end
