module Dodopayments
  module Models
    type credit_entitlement_undelete_params =
      { id: String } & Dodopayments::Internal::Type::request_parameters

    class CreditEntitlementUndeleteParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
