module Dodopayments
  module Models
    type credit_rolled_over_webhook_event =
      {
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: :"credit.rolled_over"
      }

    class CreditRolledOverWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::CreditEntitlements::CreditLedgerEntry

      attr_accessor timestamp: Time

      attr_accessor type: :"credit.rolled_over"

      def initialize: (
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        ?type: :"credit.rolled_over"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: :"credit.rolled_over"
      }
    end
  end
end
