module Dodopayments
  module Models
    type credit_deducted_webhook_event =
      {
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: Dodopayments::Models::CreditDeductedWebhookEvent::type_
      }

    class CreditDeductedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::CreditEntitlements::CreditLedgerEntry

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::CreditDeductedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: Dodopayments::Models::CreditDeductedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: Dodopayments::Models::CreditDeductedWebhookEvent::type_
      }

      type type_ = :"credit.deducted"

      module Type
        extend Dodopayments::Internal::Type::Enum

        CREDIT_DEDUCTED: :"credit.deducted"

        def self?.values: -> ::Array[Dodopayments::Models::CreditDeductedWebhookEvent::type_]
      end
    end
  end
end
