module Dodopayments
  module Models
    type credit_overage_charged_webhook_event =
      {
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: Dodopayments::Models::CreditOverageChargedWebhookEvent::type_
      }

    class CreditOverageChargedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::CreditEntitlements::CreditLedgerEntry

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::CreditOverageChargedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: Dodopayments::Models::CreditOverageChargedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::CreditEntitlements::CreditLedgerEntry,
        timestamp: Time,
        type: Dodopayments::Models::CreditOverageChargedWebhookEvent::type_
      }

      type type_ = :"credit.overage_charged"

      module Type
        extend Dodopayments::Internal::Type::Enum

        CREDIT_OVERAGE_CHARGED: :"credit.overage_charged"

        def self?.values: -> ::Array[Dodopayments::Models::CreditOverageChargedWebhookEvent::type_]
      end
    end
  end
end
