module Dodopayments
  module Models
    type customer_request =
      Dodopayments::AttachExistingCustomer | Dodopayments::NewCustomer

    module CustomerRequest
      extend Dodopayments::Internal::Type::Union

      def self?.variants: -> ::Array[Dodopayments::Models::customer_request]
    end
  end
end
