module Dodopayments
  module Models
    type customer_portal_session = { link: String }

    class CustomerPortalSession < Dodopayments::BaseModel
      attr_accessor link: String

      def initialize:
        (link: String) -> void
        | (
          ?Dodopayments::Models::customer_portal_session
          | Dodopayments::BaseModel data
        ) -> void

      def to_hash: -> Dodopayments::Models::customer_portal_session
    end
  end
end
