module Dodopayments
  module Models
    type customer_limited_details =
      { customer_id: String, email: String, name: String }

    class CustomerLimitedDetails < Dodopayments::Internal::Type::BaseModel
      attr_accessor customer_id: String

      attr_accessor email: String

      attr_accessor name: String

      def initialize: (customer_id: String, email: String, name: String) -> void

      def to_hash: -> Dodopayments::Models::customer_limited_details
    end
  end
end
