module Dodopayments
  module Models
    type customer_request =
      Dodopayments::Models::AttachExistingCustomer
      | Dodopayments::Models::CreateNewCustomer

    module CustomerRequest
      extend Dodopayments::Union

      def self.variants: -> [Dodopayments::Models::AttachExistingCustomer, Dodopayments::Models::CreateNewCustomer]
    end
  end
end
