module Dodopayments
  module Models
    type customer_update_params =
      {
        metadata: ::Hash[Symbol, String]?,
        name: String?,
        phone_number: String?
      }
      & Dodopayments::Internal::Type::request_parameters

    class CustomerUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_accessor name: String?

      attr_accessor phone_number: String?

      def initialize: (
        ?metadata: ::Hash[Symbol, String]?,
        ?name: String?,
        ?phone_number: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        metadata: ::Hash[Symbol, String]?,
        name: String?,
        phone_number: String?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
