module Dodopayments
  module Models
    type discount_update_params =
      {
        amount: Integer?,
        code: String?,
        expires_at: Time?,
        name: String?,
        restricted_to: ::Array[String]?,
        type: Dodopayments::Models::discount_type?,
        usage_limit: Integer?
      }
      & Dodopayments::Internal::Type::request_parameters

    class DiscountUpdateParams < Dodopayments::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor amount: Integer?

      attr_accessor code: String?

      attr_accessor expires_at: Time?

      attr_accessor name: String?

      attr_accessor restricted_to: ::Array[String]?

      attr_accessor type: Dodopayments::Models::discount_type?

      attr_accessor usage_limit: Integer?

      def initialize: (
        ?amount: Integer?,
        ?code: String?,
        ?expires_at: Time?,
        ?name: String?,
        ?restricted_to: ::Array[String]?,
        ?type: Dodopayments::Models::discount_type?,
        ?usage_limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> Dodopayments::Models::discount_update_params
    end
  end
end
