module Dodopayments
  module Models
    type discount_delete_params = {  } & Dodopayments::request_parameters

    class DiscountDeleteParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> Dodopayments::Models::discount_delete_params
    end
  end
end
