module Dodopayments
  module Models
    type discount_update_params =
      {
        discount_id: String,
        amount: Integer?,
        code: String?,
        currency_options: ::Array[Dodopayments::DiscountUpdateParams::CurrencyOption]?,
        customer_eligibility: Dodopayments::Models::DiscountUpdateParams::customer_eligibility?,
        expires_at: Time?,
        metadata: Dodopayments::Models::metadata?,
        name: String?,
        per_customer_usage_limit: Integer?,
        preserve_on_plan_change: bool?,
        restricted_to: ::Array[String]?,
        starts_at: Time?,
        subscription_cycles: Integer?,
        type: Dodopayments::Models::discount_type?,
        usage_limit: Integer?
      }
      & Dodopayments::Internal::Type::request_parameters

    class DiscountUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor discount_id: String

      attr_accessor amount: Integer?

      attr_accessor code: String?

      attr_accessor currency_options: ::Array[Dodopayments::DiscountUpdateParams::CurrencyOption]?

      attr_accessor customer_eligibility: Dodopayments::Models::DiscountUpdateParams::customer_eligibility?

      attr_accessor expires_at: Time?

      attr_accessor metadata: Dodopayments::Models::metadata?

      attr_accessor name: String?

      attr_accessor per_customer_usage_limit: Integer?

      attr_accessor preserve_on_plan_change: bool?

      attr_accessor restricted_to: ::Array[String]?

      attr_accessor starts_at: Time?

      attr_accessor subscription_cycles: Integer?

      attr_accessor type: Dodopayments::Models::discount_type?

      attr_accessor usage_limit: Integer?

      def initialize: (
        discount_id: String,
        ?amount: Integer?,
        ?code: String?,
        ?currency_options: ::Array[Dodopayments::DiscountUpdateParams::CurrencyOption]?,
        ?customer_eligibility: Dodopayments::Models::DiscountUpdateParams::customer_eligibility?,
        ?expires_at: Time?,
        ?metadata: Dodopayments::Models::metadata?,
        ?name: String?,
        ?per_customer_usage_limit: Integer?,
        ?preserve_on_plan_change: bool?,
        ?restricted_to: ::Array[String]?,
        ?starts_at: Time?,
        ?subscription_cycles: Integer?,
        ?type: Dodopayments::Models::discount_type?,
        ?usage_limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        discount_id: String,
        amount: Integer?,
        code: String?,
        currency_options: ::Array[Dodopayments::DiscountUpdateParams::CurrencyOption]?,
        customer_eligibility: Dodopayments::Models::DiscountUpdateParams::customer_eligibility?,
        expires_at: Time?,
        metadata: Dodopayments::Models::metadata?,
        name: String?,
        per_customer_usage_limit: Integer?,
        preserve_on_plan_change: bool?,
        restricted_to: ::Array[String]?,
        starts_at: Time?,
        subscription_cycles: Integer?,
        type: Dodopayments::Models::discount_type?,
        usage_limit: Integer?,
        request_options: Dodopayments::RequestOptions
      }

      type currency_option =
        {
          currency: Dodopayments::Models::currency,
          is_default: bool,
          max_amount_possible: Integer?,
          minimum_subtotal: Integer
        }

      class CurrencyOption < Dodopayments::Internal::Type::BaseModel
        attr_accessor currency: Dodopayments::Models::currency

        attr_reader is_default: bool?

        def is_default=: (bool) -> bool

        attr_accessor max_amount_possible: Integer?

        attr_reader minimum_subtotal: Integer?

        def minimum_subtotal=: (Integer) -> Integer

        def initialize: (
          currency: Dodopayments::Models::currency,
          ?is_default: bool,
          ?max_amount_possible: Integer?,
          ?minimum_subtotal: Integer
        ) -> void

        def to_hash: -> {
          currency: Dodopayments::Models::currency,
          is_default: bool,
          max_amount_possible: Integer?,
          minimum_subtotal: Integer
        }
      end

      type customer_eligibility = :any | :first_time | :existing | :specific

      module CustomerEligibility
        extend Dodopayments::Internal::Type::Enum

        ANY: :any
        FIRST_TIME: :first_time
        EXISTING: :existing
        SPECIFIC: :specific

        def self?.values: -> ::Array[Dodopayments::Models::DiscountUpdateParams::customer_eligibility]
      end
    end
  end
end
