module Dodopayments
  module Models
    type discount_type = :percentage

    module DiscountType
      extend Dodopayments::Internal::Type::Enum

      PERCENTAGE: :percentage

      def self?.values: -> ::Array[Dodopayments::Models::discount_type]
    end
  end
end
