module Dodopayments
  module Models
    type discount_retrieve_by_code_params =
      { code: String } & Dodopayments::Internal::Type::request_parameters

    class DiscountRetrieveByCodeParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor code: String

      def initialize: (
        code: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        code: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
