module Dodopayments
  module Models
    type discount_create_params =
      {
        amount: Integer,
        type: Dodopayments::Models::discount_type,
        code: String?,
        expires_at: Time?,
        name: String?,
        restricted_to: ::Array[String]?,
        usage_limit: Integer?
      }
      & Dodopayments::Internal::Type::request_parameters

    class DiscountCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor amount: Integer

      attr_accessor type: Dodopayments::Models::discount_type

      attr_accessor code: String?

      attr_accessor expires_at: Time?

      attr_accessor name: String?

      attr_accessor restricted_to: ::Array[String]?

      attr_accessor usage_limit: Integer?

      def initialize: (
        amount: Integer,
        type: Dodopayments::Models::discount_type,
        ?code: String?,
        ?expires_at: Time?,
        ?name: String?,
        ?restricted_to: ::Array[String]?,
        ?usage_limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> void
    end
  end
end
