module Dodopayments
  module Models
    type discount_retrieve_params =
      { discount_id: String } & Dodopayments::Internal::Type::request_parameters

    class DiscountRetrieveParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor discount_id: String

      def initialize: (
        discount_id: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        discount_id: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
