module Dodopayments
  module Models
    type discount_list_params =
      {
        active: bool,
        code: String,
        discount_type: Dodopayments::Models::discount_type,
        page_number: Integer,
        page_size: Integer,
        product_id: String
      }
      & Dodopayments::Internal::Type::request_parameters

    class DiscountListParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_reader active: bool?

      def active=: (bool) -> bool

      attr_reader code: String?

      def code=: (String) -> String

      attr_reader discount_type: Dodopayments::Models::discount_type?

      def discount_type=: (
        Dodopayments::Models::discount_type
      ) -> Dodopayments::Models::discount_type

      attr_reader page_number: Integer?

      def page_number=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader product_id: String?

      def product_id=: (String) -> String

      def initialize: (
        ?active: bool,
        ?code: String,
        ?discount_type: Dodopayments::Models::discount_type,
        ?page_number: Integer,
        ?page_size: Integer,
        ?product_id: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        active: bool,
        code: String,
        discount_type: Dodopayments::Models::discount_type,
        page_number: Integer,
        page_size: Integer,
        product_id: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
