module Dodopayments
  module Models
    type discount_delete_params =
      {  } & Dodopayments::Internal::Type::request_parameters

    class DiscountDeleteParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void
    end
  end
end
