module Dodopayments
  module Models
    type dispute_retrieve_params = {  } & Dodopayments::request_parameters

    class DisputeRetrieveParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> Dodopayments::Models::dispute_retrieve_params
    end
  end
end
