module Dodopayments
  module Models
    type dispute_stage = :pre_dispute | :dispute | :pre_arbitration

    module DisputeStage
      extend Dodopayments::Internal::Type::Enum

      PRE_DISPUTE: :pre_dispute
      DISPUTE: :dispute
      PRE_ARBITRATION: :pre_arbitration

      def self?.values: -> ::Array[Dodopayments::Models::dispute_stage]
    end
  end
end
