module Dodopayments
  module Models
    type dispute_accepted_webhook_event =
      {
        business_id: String,
        data: Dodopayments::DisputeAcceptedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_
      }

    class DisputeAcceptedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::DisputeAcceptedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::DisputeAcceptedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::DisputeAcceptedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_
      }

      type data =
        {
          payload_type: Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type
        }

      class Data < Dodopayments::Models::Dispute
        def payload_type: -> Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type?

        def payload_type=: (
          Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type _
        ) -> Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type

        def initialize: (
          ?payload_type: Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type
        ) -> void

        def to_hash: -> {
          payload_type: Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type
        }

        type payload_type = :Dispute

        module PayloadType
          extend Dodopayments::Internal::Type::Enum

          DISPUTE: :Dispute

          def self?.values: -> ::Array[Dodopayments::Models::DisputeAcceptedWebhookEvent::Data::payload_type]
        end
      end

      type type_ = :"dispute.accepted"

      module Type
        extend Dodopayments::Internal::Type::Enum

        DISPUTE_ACCEPTED: :"dispute.accepted"

        def self?.values: -> ::Array[Dodopayments::Models::DisputeAcceptedWebhookEvent::type_]
      end
    end
  end
end
