module Dodopayments
  module Models
    type dispute_accepted_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Dispute,
        timestamp: Time,
        type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_
      }

    class DisputeAcceptedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Dispute

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Dispute,
        timestamp: Time,
        type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Dispute,
        timestamp: Time,
        type: Dodopayments::Models::DisputeAcceptedWebhookEvent::type_
      }

      type type_ = :"dispute.accepted"

      module Type
        extend Dodopayments::Internal::Type::Enum

        DISPUTE_ACCEPTED: :"dispute.accepted"

        def self?.values: -> ::Array[Dodopayments::Models::DisputeAcceptedWebhookEvent::type_]
      end
    end
  end
end
