module Dodopayments
  module Models
    type dispute_won_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Dispute,
        timestamp: Time,
        type: :"dispute.won"
      }

    class DisputeWonWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Dispute

      attr_accessor timestamp: Time

      attr_accessor type: :"dispute.won"

      def initialize: (
        business_id: String,
        data: Dodopayments::Dispute,
        timestamp: Time,
        ?type: :"dispute.won"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Dispute,
        timestamp: Time,
        type: :"dispute.won"
      }
    end
  end
end
