module Dodopayments
  module Models
    type dunning_started_webhook_event =
      {
        business_id: String,
        data: Dodopayments::DunningStartedWebhookEvent::Data,
        timestamp: Time,
        type: :"dunning.started"
      }

    class DunningStartedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::DunningStartedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"dunning.started"

      def initialize: (
        business_id: String,
        data: Dodopayments::DunningStartedWebhookEvent::Data,
        timestamp: Time,
        ?type: :"dunning.started"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::DunningStartedWebhookEvent::Data,
        timestamp: Time,
        type: :"dunning.started"
      }

      type data =
        {
          brand_id: String,
          created_at: Time,
          customer_id: String,
          status: Dodopayments::Models::DunningStartedWebhookEvent::Data::status,
          subscription_id: String,
          trigger_state: Dodopayments::Models::DunningStartedWebhookEvent::Data::trigger_state,
          payment_id: String?
        }

      class Data < Dodopayments::Internal::Type::BaseModel
        attr_accessor brand_id: String

        attr_accessor created_at: Time

        attr_accessor customer_id: String

        attr_accessor status: Dodopayments::Models::DunningStartedWebhookEvent::Data::status

        attr_accessor subscription_id: String

        attr_accessor trigger_state: Dodopayments::Models::DunningStartedWebhookEvent::Data::trigger_state

        attr_accessor payment_id: String?

        def initialize: (
          brand_id: String,
          created_at: Time,
          customer_id: String,
          status: Dodopayments::Models::DunningStartedWebhookEvent::Data::status,
          subscription_id: String,
          trigger_state: Dodopayments::Models::DunningStartedWebhookEvent::Data::trigger_state,
          ?payment_id: String?
        ) -> void

        def to_hash: -> {
          brand_id: String,
          created_at: Time,
          customer_id: String,
          status: Dodopayments::Models::DunningStartedWebhookEvent::Data::status,
          subscription_id: String,
          trigger_state: Dodopayments::Models::DunningStartedWebhookEvent::Data::trigger_state,
          payment_id: String?
        }

        type status = :recovering | :recovered | :exhausted

        module Status
          extend Dodopayments::Internal::Type::Enum

          RECOVERING: :recovering
          RECOVERED: :recovered
          EXHAUSTED: :exhausted

          def self?.values: -> ::Array[Dodopayments::Models::DunningStartedWebhookEvent::Data::status]
        end

        type trigger_state = :on_hold | :cancelled

        module TriggerState
          extend Dodopayments::Internal::Type::Enum

          ON_HOLD: :on_hold
          CANCELLED: :cancelled

          def self?.values: -> ::Array[Dodopayments::Models::DunningStartedWebhookEvent::Data::trigger_state]
        end
      end
    end
  end
end
