module Dodopayments
  module Models
    type entitlement_create_params =
      {
        integration_config: Dodopayments::Models::integration_config,
        integration_type: Dodopayments::Models::entitlement_integration_type,
        name: String,
        description: String?,
        metadata: ::Hash[Symbol, String]?
      }
      & Dodopayments::Internal::Type::request_parameters

    class EntitlementCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor integration_config: Dodopayments::Models::integration_config

      attr_accessor integration_type: Dodopayments::Models::entitlement_integration_type

      attr_accessor name: String

      attr_accessor description: String?

      attr_accessor metadata: ::Hash[Symbol, String]?

      def initialize: (
        integration_config: Dodopayments::Models::integration_config,
        integration_type: Dodopayments::Models::entitlement_integration_type,
        name: String,
        ?description: String?,
        ?metadata: ::Hash[Symbol, String]?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        integration_config: Dodopayments::Models::integration_config,
        integration_type: Dodopayments::Models::entitlement_integration_type,
        name: String,
        description: String?,
        metadata: ::Hash[Symbol, String]?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
