module Dodopayments
  module Models
    type entitlement_grant_revoked_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: Dodopayments::Models::EntitlementGrantRevokedWebhookEvent::type_
      }

    class EntitlementGrantRevokedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Entitlements::EntitlementGrant

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::EntitlementGrantRevokedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: Dodopayments::Models::EntitlementGrantRevokedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: Dodopayments::Models::EntitlementGrantRevokedWebhookEvent::type_
      }

      type type_ = :"entitlement_grant.revoked"

      module Type
        extend Dodopayments::Internal::Type::Enum

        ENTITLEMENT_GRANT_REVOKED: :"entitlement_grant.revoked"

        def self?.values: -> ::Array[Dodopayments::Models::EntitlementGrantRevokedWebhookEvent::type_]
      end
    end
  end
end
