module Dodopayments
  module Models
    type entitlement_grant_revoked_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: :"entitlement_grant.revoked"
      }

    class EntitlementGrantRevokedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Entitlements::EntitlementGrant

      attr_accessor timestamp: Time

      attr_accessor type: :"entitlement_grant.revoked"

      def initialize: (
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        ?type: :"entitlement_grant.revoked"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: :"entitlement_grant.revoked"
      }
    end
  end
end
