module Dodopayments
  module Models
    type entitlement_update_params =
      {
        id: String,
        description: String?,
        integration_config: Dodopayments::Models::integration_config?,
        metadata: ::Hash[Symbol, String]?,
        name: String?
      }
      & Dodopayments::Internal::Type::request_parameters

    class EntitlementUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor description: String?

      attr_accessor integration_config: Dodopayments::Models::integration_config?

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_accessor name: String?

      def initialize: (
        id: String,
        ?description: String?,
        ?integration_config: Dodopayments::Models::integration_config?,
        ?metadata: ::Hash[Symbol, String]?,
        ?name: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        description: String?,
        integration_config: Dodopayments::Models::integration_config?,
        metadata: ::Hash[Symbol, String]?,
        name: String?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
