module Dodopayments
  module Models
    type entitlement_grant_delivered_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: Dodopayments::Models::EntitlementGrantDeliveredWebhookEvent::type_
      }

    class EntitlementGrantDeliveredWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Entitlements::EntitlementGrant

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::EntitlementGrantDeliveredWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: Dodopayments::Models::EntitlementGrantDeliveredWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Entitlements::EntitlementGrant,
        timestamp: Time,
        type: Dodopayments::Models::EntitlementGrantDeliveredWebhookEvent::type_
      }

      type type_ = :"entitlement_grant.delivered"

      module Type
        extend Dodopayments::Internal::Type::Enum

        ENTITLEMENT_GRANT_DELIVERED: :"entitlement_grant.delivered"

        def self?.values: -> ::Array[Dodopayments::Models::EntitlementGrantDeliveredWebhookEvent::type_]
      end
    end
  end
end
