module Dodopayments
  module Models
    type license_key_instance_list_response_item =
      { items: ::Array[Dodopayments::LicenseKeyInstance] }

    class LicenseKeyInstanceListResponseItem < Dodopayments::Internal::Type::BaseModel
      attr_accessor items: ::Array[Dodopayments::LicenseKeyInstance]

      def initialize: (items: ::Array[Dodopayments::LicenseKeyInstance]) -> void

      def to_hash: -> { items: ::Array[Dodopayments::LicenseKeyInstance] }
    end

    type license_key_instance_list_response =
      ::Array[Dodopayments::Models::LicenseKeyInstanceListResponseItem]

    LicenseKeyInstanceListResponse: Dodopayments::Internal::Type::Converter
  end
end
