module Dodopayments
  module Models
    type license_key_created_webhook_event =
      {
        business_id: String,
        data: Dodopayments::LicenseKey,
        timestamp: Time,
        type: :"license_key.created"
      }

    class LicenseKeyCreatedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::LicenseKey

      attr_accessor timestamp: Time

      attr_accessor type: :"license_key.created"

      def initialize: (
        business_id: String,
        data: Dodopayments::LicenseKey,
        timestamp: Time,
        ?type: :"license_key.created"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::LicenseKey,
        timestamp: Time,
        type: :"license_key.created"
      }
    end
  end
end
