module Dodopayments
  module Models
    type license_key =
      {
        id: String,
        business_id: String,
        created_at: Time,
        customer_id: String,
        instances_count: Integer,
        key: String,
        product_id: String,
        source: Dodopayments::Models::LicenseKey::source,
        status: Dodopayments::Models::license_key_status,
        activations_limit: Integer?,
        expires_at: Time?,
        payment_id: String?,
        subscription_id: String?
      }

    class LicenseKey < Dodopayments::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor business_id: String

      attr_accessor created_at: Time

      attr_accessor customer_id: String

      attr_accessor instances_count: Integer

      attr_accessor key: String

      attr_accessor product_id: String

      attr_accessor source: Dodopayments::Models::LicenseKey::source

      attr_accessor status: Dodopayments::Models::license_key_status

      attr_accessor activations_limit: Integer?

      attr_accessor expires_at: Time?

      attr_accessor payment_id: String?

      attr_accessor subscription_id: String?

      def initialize: (
        id: String,
        business_id: String,
        created_at: Time,
        customer_id: String,
        instances_count: Integer,
        key: String,
        product_id: String,
        source: Dodopayments::Models::LicenseKey::source,
        status: Dodopayments::Models::license_key_status,
        ?activations_limit: Integer?,
        ?expires_at: Time?,
        ?payment_id: String?,
        ?subscription_id: String?
      ) -> void

      def to_hash: -> {
        id: String,
        business_id: String,
        created_at: Time,
        customer_id: String,
        instances_count: Integer,
        key: String,
        product_id: String,
        source: Dodopayments::Models::LicenseKey::source,
        status: Dodopayments::Models::license_key_status,
        activations_limit: Integer?,
        expires_at: Time?,
        payment_id: String?,
        subscription_id: String?
      }

      type source = :auto | :import

      module Source
        extend Dodopayments::Internal::Type::Enum

        AUTO: :auto
        IMPORT: :import

        def self?.values: -> ::Array[Dodopayments::Models::LicenseKey::source]
      end
    end
  end
end
