module Dodopayments
  module Models
    type license_validate_response = { valid: bool }

    class LicenseValidateResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor valid: bool

      def initialize: (valid: bool) -> void
    end
  end
end
