module Dodopayments
  module Models
    type license_key_update_params =
      { activations_limit: Integer?, disabled: bool?, expires_at: Time? }
      & Dodopayments::Internal::Type::request_parameters

    class LicenseKeyUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor activations_limit: Integer?

      attr_accessor disabled: bool?

      attr_accessor expires_at: Time?

      def initialize: (
        ?activations_limit: Integer?,
        ?disabled: bool?,
        ?expires_at: Time?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        activations_limit: Integer?,
        disabled: bool?,
        expires_at: Time?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
