module Dodopayments
  module Models
    type license_key_instance =
      {
        id: String,
        business_id: String,
        created_at: Time,
        license_key_id: String,
        name: String
      }

    class LicenseKeyInstance < Dodopayments::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor business_id: String

      attr_accessor created_at: Time

      attr_accessor license_key_id: String

      attr_accessor name: String

      def initialize: (
        id: String,
        business_id: String,
        created_at: Time,
        license_key_id: String,
        name: String
      ) -> void

      def to_hash: -> {
        id: String,
        business_id: String,
        created_at: Time,
        license_key_id: String,
        name: String
      }
    end
  end
end
