module Dodopayments
  module Models
    type license_validate_response = { valid: bool }

    class LicenseValidateResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor valid: bool

      def initialize: (valid: bool) -> void

      def to_hash: -> Dodopayments::Models::license_validate_response
    end
  end
end
