module Dodopayments
  module Models
    type license_key_created_webhook_event =
      {
        business_id: String,
        data: Dodopayments::LicenseKeyCreatedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::type_
      }

    class LicenseKeyCreatedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::LicenseKeyCreatedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::LicenseKeyCreatedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::LicenseKeyCreatedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::type_
      }

      type data =
        {
          payload_type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type
        }

      class Data < Dodopayments::Models::LicenseKey
        def payload_type: -> Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type?

        def payload_type=: (
          Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type _
        ) -> Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type

        def initialize: (
          ?payload_type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type
        ) -> void

        def to_hash: -> {
          payload_type: Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type
        }

        type payload_type = :LicenseKey

        module PayloadType
          extend Dodopayments::Internal::Type::Enum

          LICENSE_KEY: :LicenseKey

          def self?.values: -> ::Array[Dodopayments::Models::LicenseKeyCreatedWebhookEvent::Data::payload_type]
        end
      end

      type type_ = :"license_key.created"

      module Type
        extend Dodopayments::Internal::Type::Enum

        LICENSE_KEY_CREATED: :"license_key.created"

        def self?.values: -> ::Array[Dodopayments::Models::LicenseKeyCreatedWebhookEvent::type_]
      end
    end
  end
end
