module Dodopayments
  module Models
    type license_activate_params =
      { license_key: String, name: String }
      & Dodopayments::Internal::Type::request_parameters

    class LicenseActivateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor license_key: String

      attr_accessor name: String

      def initialize: (
        license_key: String,
        name: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        license_key: String,
        name: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
