module Dodopayments
  module Models
    type license_key_instance_list_params =
      { license_key_id: String?, page_number: Integer?, page_size: Integer? }
      & Dodopayments::request_parameters

    class LicenseKeyInstanceListParams < Dodopayments::BaseModel
      extend Dodopayments::Type::RequestParameters::Converter
      include Dodopayments::RequestParameters

      attr_accessor license_key_id: String?

      attr_accessor page_number: Integer?

      attr_accessor page_size: Integer?

      def initialize: (
        ?license_key_id: String?,
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> Dodopayments::Models::license_key_instance_list_params
    end
  end
end
