module Dodopayments
  module Models
    type license_key_status = :active | :expired | :disabled

    module LicenseKeyStatus
      extend Dodopayments::Enum

      ACTIVE: :active
      EXPIRED: :expired
      DISABLED: :disabled

      def self?.values: -> ::Array[Dodopayments::Models::license_key_status]
    end
  end
end
