module Dodopayments
  module Models
    type license_key_instance_retrieve_params =
      {  } & Dodopayments::Internal::Type::request_parameters

    class LicenseKeyInstanceRetrieveParams < Dodopayments::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> Dodopayments::Models::license_key_instance_retrieve_params
    end
  end
end
