module Dodopayments
  module Models
    type meter_filter =
      {
        clauses: Dodopayments::Models::filter_type,
        conjunction: Dodopayments::Models::conjunction
      }

    class MeterFilter < Dodopayments::Internal::Type::BaseModel
      attr_accessor clauses: Dodopayments::Models::filter_type

      attr_accessor conjunction: Dodopayments::Models::conjunction

      def initialize: (
        clauses: Dodopayments::Models::filter_type,
        conjunction: Dodopayments::Models::conjunction
      ) -> void

      def to_hash: -> {
        clauses: Dodopayments::Models::filter_type,
        conjunction: Dodopayments::Models::conjunction
      }
    end
  end
end
