module Dodopayments
  module Models
    type misc_list_supported_countries_params =
      {  } & Dodopayments::request_parameters

    class MiscListSupportedCountriesParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> Dodopayments::Models::misc_list_supported_countries_params
    end
  end
end
