module Dodopayments
  module Models
    type misc_list_supported_countries_response =
      ::Array[Dodopayments::Models::country_code]

    MiscListSupportedCountriesResponse: Dodopayments::Internal::Type::Converter
  end
end
