module Dodopayments
  module Models
    type moderation_category =
      :violent_crimes
      | :sex_related_crimes
      | :child_sexual_exploitation
      | :suicide_and_self_harm
      | :indiscriminate_weapons
      | :intellectual_property
      | :defamation
      | :non_violent_crimes
      | :hate
      | :privacy
      | :specialized_advice
      | :sexual_content
      | :non_consensual_intimate_imagery
      | :minor_coded_language
      | :real_person_likeness
      | :living_artist_style
      | :prompt_injection

    module ModerationCategory
      extend Dodopayments::Internal::Type::Enum

      VIOLENT_CRIMES: :violent_crimes
      SEX_RELATED_CRIMES: :sex_related_crimes
      CHILD_SEXUAL_EXPLOITATION: :child_sexual_exploitation
      SUICIDE_AND_SELF_HARM: :suicide_and_self_harm
      INDISCRIMINATE_WEAPONS: :indiscriminate_weapons
      INTELLECTUAL_PROPERTY: :intellectual_property
      DEFAMATION: :defamation
      NON_VIOLENT_CRIMES: :non_violent_crimes
      HATE: :hate
      PRIVACY: :privacy
      SPECIALIZED_ADVICE: :specialized_advice
      SEXUAL_CONTENT: :sexual_content
      NON_CONSENSUAL_INTIMATE_IMAGERY: :non_consensual_intimate_imagery
      MINOR_CODED_LANGUAGE: :minor_coded_language
      REAL_PERSON_LIKENESS: :real_person_likeness
      LIVING_ARTIST_STYLE: :living_artist_style
      PROMPT_INJECTION: :prompt_injection

      def self?.values: -> ::Array[Dodopayments::Models::moderation_category]
    end
  end
end
