module Dodopayments
  module Models
    type on_demand_subscription =
      {
        mandate_only: bool,
        adaptive_currency_fees_inclusive: bool?,
        product_currency: Dodopayments::Models::currency?,
        product_description: String?,
        product_price: Integer?
      }

    class OnDemandSubscription < Dodopayments::Internal::Type::BaseModel
      attr_accessor mandate_only: bool

      attr_accessor adaptive_currency_fees_inclusive: bool?

      attr_accessor product_currency: Dodopayments::Models::currency?

      attr_accessor product_description: String?

      attr_accessor product_price: Integer?

      def initialize: (
        mandate_only: bool,
        ?adaptive_currency_fees_inclusive: bool?,
        ?product_currency: Dodopayments::Models::currency?,
        ?product_description: String?,
        ?product_price: Integer?
      ) -> void

      def to_hash: -> {
        mandate_only: bool,
        adaptive_currency_fees_inclusive: bool?,
        product_currency: Dodopayments::Models::currency?,
        product_description: String?,
        product_price: Integer?
      }
    end
  end
end
