module Dodopayments
  module Models
    type one_time_product_cart_item = { product_id: String, quantity: Integer }

    class OneTimeProductCartItem < Dodopayments::Internal::Type::BaseModel
      attr_accessor product_id: String

      attr_accessor quantity: Integer

      def initialize: (product_id: String, quantity: Integer) -> void

      def to_hash: -> { product_id: String, quantity: Integer }
    end
  end
end
