module Dodopayments
  module Models
    type payment_create_response =
      {
        client_secret: String,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        discount_id: String?,
        payment_link: String?,
        product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?
      }

    class PaymentCreateResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor client_secret: String

      attr_accessor customer: Dodopayments::CustomerLimitedDetails

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor payment_id: String

      attr_accessor total_amount: Integer

      attr_accessor discount_id: String?

      attr_accessor payment_link: String?

      attr_accessor product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?

      def initialize: (
        client_secret: String,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        ?discount_id: String?,
        ?payment_link: String?,
        ?product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?
      ) -> void

      def to_hash: -> {
        client_secret: String,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        discount_id: String?,
        payment_link: String?,
        product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?
      }
    end
  end
end
