module Dodopayments
  module Models
    type payment_failed_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Payment,
        timestamp: Time,
        type: :"payment.failed"
      }

    class PaymentFailedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Payment

      attr_accessor timestamp: Time

      attr_accessor type: :"payment.failed"

      def initialize: (
        business_id: String,
        data: Dodopayments::Payment,
        timestamp: Time,
        ?type: :"payment.failed"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Payment,
        timestamp: Time,
        type: :"payment.failed"
      }
    end
  end
end
