module Dodopayments
  module Models
    type payment_create_response =
      {
        client_secret: String,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        discount_id: String?,
        expires_on: Time?,
        payment_link: String?,
        product_cart: ::Array[Dodopayments::Models::PaymentCreateResponse::ProductCart]?
      }

    class PaymentCreateResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor client_secret: String

      attr_accessor customer: Dodopayments::CustomerLimitedDetails

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor payment_id: String

      attr_accessor total_amount: Integer

      attr_accessor discount_id: String?

      attr_accessor expires_on: Time?

      attr_accessor payment_link: String?

      attr_accessor product_cart: ::Array[Dodopayments::Models::PaymentCreateResponse::ProductCart]?

      def initialize: (
        client_secret: String,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        ?discount_id: String?,
        ?expires_on: Time?,
        ?payment_link: String?,
        ?product_cart: ::Array[Dodopayments::Models::PaymentCreateResponse::ProductCart]?
      ) -> void

      def to_hash: -> {
        client_secret: String,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        discount_id: String?,
        expires_on: Time?,
        payment_link: String?,
        product_cart: ::Array[Dodopayments::Models::PaymentCreateResponse::ProductCart]?
      }

      type product_cart =
        { product_id: String, quantity: Integer, amount: Integer? }

      class ProductCart < Dodopayments::Internal::Type::BaseModel
        attr_accessor product_id: String

        attr_accessor quantity: Integer

        attr_accessor amount: Integer?

        def initialize: (
          product_id: String,
          quantity: Integer,
          ?amount: Integer?
        ) -> void

        def to_hash: -> {
          product_id: String,
          quantity: Integer,
          amount: Integer?
        }
      end
    end
  end
end
