module Dodopayments
  module Models
    type payment_create_params =
      {
        billing: Dodopayments::Models::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_cart: ::Array[Dodopayments::Models::OneTimeProductCartItem],
        allowed_payment_method_types: ::Array[Dodopayments::Models::PaymentCreateParams::allowed_payment_method_type]?,
        billing_currency: Dodopayments::Models::PaymentCreateParams::billing_currency?,
        discount_code: String?,
        metadata: ::Hash[Symbol, String],
        payment_link: bool?,
        return_url: String?,
        show_saved_payment_methods: bool,
        tax_id: String?
      }
      & Dodopayments::Internal::Type::request_parameters

    class PaymentCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor billing: Dodopayments::Models::BillingAddress

      attr_accessor customer: Dodopayments::Models::customer_request

      attr_accessor product_cart: ::Array[Dodopayments::Models::OneTimeProductCartItem]

      attr_accessor allowed_payment_method_types: ::Array[Dodopayments::Models::PaymentCreateParams::allowed_payment_method_type]?

      attr_accessor billing_currency: Dodopayments::Models::PaymentCreateParams::billing_currency?

      attr_accessor discount_code: String?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_accessor payment_link: bool?

      attr_accessor return_url: String?

      attr_reader show_saved_payment_methods: bool?

      def show_saved_payment_methods=: (bool) -> bool

      attr_accessor tax_id: String?

      def initialize: (
        billing: Dodopayments::Models::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_cart: ::Array[Dodopayments::Models::OneTimeProductCartItem],
        ?allowed_payment_method_types: ::Array[Dodopayments::Models::PaymentCreateParams::allowed_payment_method_type]?,
        ?billing_currency: Dodopayments::Models::PaymentCreateParams::billing_currency?,
        ?discount_code: String?,
        ?metadata: ::Hash[Symbol, String],
        ?payment_link: bool?,
        ?return_url: String?,
        ?show_saved_payment_methods: bool,
        ?tax_id: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> Dodopayments::Models::payment_create_params

      type allowed_payment_method_type =
        :credit
        | :debit
        | :upi_collect
        | :upi_intent
        | :apple_pay
        | :cashapp
        | :google_pay
        | :multibanco
        | :bancontact_card
        | :eps
        | :ideal
        | :przelewy24
        | :affirm
        | :klarna
        | :sepa
        | :ach
        | :amazon_pay
        | :afterpay_clearpay

      module AllowedPaymentMethodType
        extend Dodopayments::Internal::Type::Enum

        CREDIT: :credit
        DEBIT: :debit
        UPI_COLLECT: :upi_collect
        UPI_INTENT: :upi_intent
        APPLE_PAY: :apple_pay
        CASHAPP: :cashapp
        GOOGLE_PAY: :google_pay
        MULTIBANCO: :multibanco
        BANCONTACT_CARD: :bancontact_card
        EPS: :eps
        IDEAL: :ideal
        PRZELEWY24: :przelewy24
        AFFIRM: :affirm
        KLARNA: :klarna
        SEPA: :sepa
        ACH: :ach
        AMAZON_PAY: :amazon_pay
        AFTERPAY_CLEARPAY: :afterpay_clearpay

        def self?.values: -> ::Array[Dodopayments::Models::PaymentCreateParams::allowed_payment_method_type]
      end

      type billing_currency =
        :AED
        | :ALL
        | :AMD
        | :ANG
        | :AOA
        | :ARS
        | :AUD
        | :AWG
        | :AZN
        | :BAM
        | :BBD
        | :BDT
        | :BGN
        | :BHD
        | :BIF
        | :BMD
        | :BND
        | :BOB
        | :BRL
        | :BSD
        | :BWP
        | :BYN
        | :BZD
        | :CAD
        | :CHF
        | :CLP
        | :CNY
        | :COP
        | :CRC
        | :CUP
        | :CVE
        | :CZK
        | :DJF
        | :DKK
        | :DOP
        | :DZD
        | :EGP
        | :ETB
        | :EUR
        | :FJD
        | :FKP
        | :GBP
        | :GEL
        | :GHS
        | :GIP
        | :GMD
        | :GNF
        | :GTQ
        | :GYD
        | :HKD
        | :HNL
        | :HRK
        | :HTG
        | :HUF
        | :IDR
        | :ILS
        | :INR
        | :IQD
        | :JMD
        | :JOD
        | :JPY
        | :KES
        | :KGS
        | :KHR
        | :KMF
        | :KRW
        | :KWD
        | :KYD
        | :KZT
        | :LAK
        | :LBP
        | :LKR
        | :LRD
        | :LSL
        | :LYD
        | :MAD
        | :MDL
        | :MGA
        | :MKD
        | :MMK
        | :MNT
        | :MOP
        | :MRU
        | :MUR
        | :MVR
        | :MWK
        | :MXN
        | :MYR
        | :MZN
        | :NAD
        | :NGN
        | :NIO
        | :NOK
        | :NPR
        | :NZD
        | :OMR
        | :PAB
        | :PEN
        | :PGK
        | :PHP
        | :PKR
        | :PLN
        | :PYG
        | :QAR
        | :RON
        | :RSD
        | :RUB
        | :RWF
        | :SAR
        | :SBD
        | :SCR
        | :SEK
        | :SGD
        | :SHP
        | :SLE
        | :SLL
        | :SOS
        | :SRD
        | :SSP
        | :STN
        | :SVC
        | :SZL
        | :THB
        | :TND
        | :TOP
        | :TRY
        | :TTD
        | :TWD
        | :TZS
        | :UAH
        | :UGX
        | :USD
        | :UYU
        | :UZS
        | :VES
        | :VND
        | :VUV
        | :WST
        | :XAF
        | :XCD
        | :XOF
        | :XPF
        | :YER
        | :ZAR
        | :ZMW

      module BillingCurrency
        extend Dodopayments::Internal::Type::Enum

        AED: :AED
        ALL: :ALL
        AMD: :AMD
        ANG: :ANG
        AOA: :AOA
        ARS: :ARS
        AUD: :AUD
        AWG: :AWG
        AZN: :AZN
        BAM: :BAM
        BBD: :BBD
        BDT: :BDT
        BGN: :BGN
        BHD: :BHD
        BIF: :BIF
        BMD: :BMD
        BND: :BND
        BOB: :BOB
        BRL: :BRL
        BSD: :BSD
        BWP: :BWP
        BYN: :BYN
        BZD: :BZD
        CAD: :CAD
        CHF: :CHF
        CLP: :CLP
        CNY: :CNY
        COP: :COP
        CRC: :CRC
        CUP: :CUP
        CVE: :CVE
        CZK: :CZK
        DJF: :DJF
        DKK: :DKK
        DOP: :DOP
        DZD: :DZD
        EGP: :EGP
        ETB: :ETB
        EUR: :EUR
        FJD: :FJD
        FKP: :FKP
        GBP: :GBP
        GEL: :GEL
        GHS: :GHS
        GIP: :GIP
        GMD: :GMD
        GNF: :GNF
        GTQ: :GTQ
        GYD: :GYD
        HKD: :HKD
        HNL: :HNL
        HRK: :HRK
        HTG: :HTG
        HUF: :HUF
        IDR: :IDR
        ILS: :ILS
        INR: :INR
        IQD: :IQD
        JMD: :JMD
        JOD: :JOD
        JPY: :JPY
        KES: :KES
        KGS: :KGS
        KHR: :KHR
        KMF: :KMF
        KRW: :KRW
        KWD: :KWD
        KYD: :KYD
        KZT: :KZT
        LAK: :LAK
        LBP: :LBP
        LKR: :LKR
        LRD: :LRD
        LSL: :LSL
        LYD: :LYD
        MAD: :MAD
        MDL: :MDL
        MGA: :MGA
        MKD: :MKD
        MMK: :MMK
        MNT: :MNT
        MOP: :MOP
        MRU: :MRU
        MUR: :MUR
        MVR: :MVR
        MWK: :MWK
        MXN: :MXN
        MYR: :MYR
        MZN: :MZN
        NAD: :NAD
        NGN: :NGN
        NIO: :NIO
        NOK: :NOK
        NPR: :NPR
        NZD: :NZD
        OMR: :OMR
        PAB: :PAB
        PEN: :PEN
        PGK: :PGK
        PHP: :PHP
        PKR: :PKR
        PLN: :PLN
        PYG: :PYG
        QAR: :QAR
        RON: :RON
        RSD: :RSD
        RUB: :RUB
        RWF: :RWF
        SAR: :SAR
        SBD: :SBD
        SCR: :SCR
        SEK: :SEK
        SGD: :SGD
        SHP: :SHP
        SLE: :SLE
        SLL: :SLL
        SOS: :SOS
        SRD: :SRD
        SSP: :SSP
        STN: :STN
        SVC: :SVC
        SZL: :SZL
        THB: :THB
        TND: :TND
        TOP: :TOP
        TRY: :TRY
        TTD: :TTD
        TWD: :TWD
        TZS: :TZS
        UAH: :UAH
        UGX: :UGX
        USD: :USD
        UYU: :UYU
        UZS: :UZS
        VES: :VES
        VND: :VND
        VUV: :VUV
        WST: :WST
        XAF: :XAF
        XCD: :XCD
        XOF: :XOF
        XPF: :XPF
        YER: :YER
        ZAR: :ZAR
        ZMW: :ZMW

        def self?.values: -> ::Array[Dodopayments::Models::PaymentCreateParams::billing_currency]
      end
    end
  end
end
