module Dodopayments
  module Models
    type payment_list_response =
      {
        created_at: Time,
        currency: Dodopayments::Models::currency,
        customer: Dodopayments::Models::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        payment_method: String?,
        payment_method_type: String?,
        status: Dodopayments::Models::intent_status?,
        subscription_id: String?
      }

    class PaymentListResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor created_at: Time

      attr_accessor currency: Dodopayments::Models::currency

      attr_accessor customer: Dodopayments::Models::CustomerLimitedDetails

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor payment_id: String

      attr_accessor total_amount: Integer

      attr_accessor payment_method: String?

      attr_accessor payment_method_type: String?

      attr_accessor status: Dodopayments::Models::intent_status?

      attr_accessor subscription_id: String?

      def initialize: (
        created_at: Time,
        currency: Dodopayments::Models::currency,
        customer: Dodopayments::Models::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        total_amount: Integer,
        ?payment_method: String?,
        ?payment_method_type: String?,
        ?status: Dodopayments::Models::intent_status?,
        ?subscription_id: String?
      ) -> void

      def to_hash: -> Dodopayments::Models::payment_list_response
    end
  end
end
