module Dodopayments
  module Models
    type payment_succeeded_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Payment,
        timestamp: Time,
        type: Dodopayments::Models::PaymentSucceededWebhookEvent::type_
      }

    class PaymentSucceededWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Payment

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::PaymentSucceededWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Payment,
        timestamp: Time,
        type: Dodopayments::Models::PaymentSucceededWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Payment,
        timestamp: Time,
        type: Dodopayments::Models::PaymentSucceededWebhookEvent::type_
      }

      type type_ = :"payment.succeeded"

      module Type
        extend Dodopayments::Internal::Type::Enum

        PAYMENT_SUCCEEDED: :"payment.succeeded"

        def self?.values: -> ::Array[Dodopayments::Models::PaymentSucceededWebhookEvent::type_]
      end
    end
  end
end
