module Dodopayments
  module Models
    type payout_list_response =
      {
        amount: Integer,
        business_id: String,
        chargebacks: Integer,
        created_at: Time,
        currency: Dodopayments::Models::currency,
        fee: Integer,
        payment_method: String,
        payout_id: String,
        refunds: Integer,
        status: Dodopayments::Models::PayoutListResponse::status,
        tax: Integer,
        updated_at: Time,
        name: String?,
        payout_document_url: String?,
        remarks: String?
      }

    class PayoutListResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor amount: Integer

      attr_accessor business_id: String

      attr_accessor chargebacks: Integer

      attr_accessor created_at: Time

      attr_accessor currency: Dodopayments::Models::currency

      attr_accessor fee: Integer

      attr_accessor payment_method: String

      attr_accessor payout_id: String

      attr_accessor refunds: Integer

      attr_accessor status: Dodopayments::Models::PayoutListResponse::status

      attr_accessor tax: Integer

      attr_accessor updated_at: Time

      attr_accessor name: String?

      attr_accessor payout_document_url: String?

      attr_accessor remarks: String?

      def initialize: (
        amount: Integer,
        business_id: String,
        chargebacks: Integer,
        created_at: Time,
        currency: Dodopayments::Models::currency,
        fee: Integer,
        payment_method: String,
        payout_id: String,
        refunds: Integer,
        status: Dodopayments::Models::PayoutListResponse::status,
        tax: Integer,
        updated_at: Time,
        ?name: String?,
        ?payout_document_url: String?,
        ?remarks: String?
      ) -> void

      type status =
        :not_initiated | :in_progress | :on_hold | :failed | :success

      module Status
        extend Dodopayments::Internal::Type::Enum

        NOT_INITIATED: :not_initiated
        IN_PROGRESS: :in_progress
        ON_HOLD: :on_hold
        FAILED: :failed
        SUCCESS: :success

        def self?.values: -> ::Array[Dodopayments::Models::PayoutListResponse::status]
      end
    end
  end
end
