module Dodopayments
  module Models
    type price =
      Dodopayments::Price::OneTimePrice
      | Dodopayments::Price::RecurringPrice
      | Dodopayments::Price::UsageBasedPrice

    module Price
      extend Dodopayments::Internal::Type::Union

      type one_time_price =
        {
          currency: Dodopayments::Models::currency,
          price: Integer,
          type: :one_time_price,
          discount: Integer,
          discount_bps: Integer?,
          pay_what_you_want: bool,
          purchasing_power_parity: bool,
          suggested_price: Integer?,
          tax_inclusive: bool?
        }

      class OneTimePrice < Dodopayments::Internal::Type::BaseModel
        attr_accessor currency: Dodopayments::Models::currency

        attr_accessor price: Integer

        attr_accessor type: :one_time_price

        attr_reader discount: Integer?

        def discount=: (Integer) -> Integer

        attr_accessor discount_bps: Integer?

        attr_reader pay_what_you_want: bool?

        def pay_what_you_want=: (bool) -> bool

        attr_reader purchasing_power_parity: bool?

        def purchasing_power_parity=: (bool) -> bool

        attr_accessor suggested_price: Integer?

        attr_accessor tax_inclusive: bool?

        def initialize: (
          currency: Dodopayments::Models::currency,
          price: Integer,
          ?discount: Integer,
          ?discount_bps: Integer?,
          ?pay_what_you_want: bool,
          ?purchasing_power_parity: bool,
          ?suggested_price: Integer?,
          ?tax_inclusive: bool?,
          ?type: :one_time_price
        ) -> void

        def to_hash: -> {
          currency: Dodopayments::Models::currency,
          price: Integer,
          type: :one_time_price,
          discount: Integer,
          discount_bps: Integer?,
          pay_what_you_want: bool,
          purchasing_power_parity: bool,
          suggested_price: Integer?,
          tax_inclusive: bool?
        }
      end

      type recurring_price =
        {
          currency: Dodopayments::Models::currency,
          payment_frequency_count: Integer,
          payment_frequency_interval: Dodopayments::Models::time_interval,
          price: Integer,
          subscription_period_count: Integer,
          subscription_period_interval: Dodopayments::Models::time_interval,
          type: :recurring_price,
          discount: Integer,
          discount_bps: Integer?,
          purchasing_power_parity: bool,
          tax_inclusive: bool?,
          trial_amount: Integer?,
          trial_apply_discounts: bool?,
          trial_payment_method_optional: bool,
          trial_period_days: Integer,
          zero_amount_payment_method_optional: bool
        }

      class RecurringPrice < Dodopayments::Internal::Type::BaseModel
        attr_accessor currency: Dodopayments::Models::currency

        attr_accessor payment_frequency_count: Integer

        attr_accessor payment_frequency_interval: Dodopayments::Models::time_interval

        attr_accessor price: Integer

        attr_accessor subscription_period_count: Integer

        attr_accessor subscription_period_interval: Dodopayments::Models::time_interval

        attr_accessor type: :recurring_price

        attr_reader discount: Integer?

        def discount=: (Integer) -> Integer

        attr_accessor discount_bps: Integer?

        attr_reader purchasing_power_parity: bool?

        def purchasing_power_parity=: (bool) -> bool

        attr_accessor tax_inclusive: bool?

        attr_accessor trial_amount: Integer?

        attr_accessor trial_apply_discounts: bool?

        attr_reader trial_payment_method_optional: bool?

        def trial_payment_method_optional=: (bool) -> bool

        attr_reader trial_period_days: Integer?

        def trial_period_days=: (Integer) -> Integer

        attr_reader zero_amount_payment_method_optional: bool?

        def zero_amount_payment_method_optional=: (bool) -> bool

        def initialize: (
          currency: Dodopayments::Models::currency,
          payment_frequency_count: Integer,
          payment_frequency_interval: Dodopayments::Models::time_interval,
          price: Integer,
          subscription_period_count: Integer,
          subscription_period_interval: Dodopayments::Models::time_interval,
          ?discount: Integer,
          ?discount_bps: Integer?,
          ?purchasing_power_parity: bool,
          ?tax_inclusive: bool?,
          ?trial_amount: Integer?,
          ?trial_apply_discounts: bool?,
          ?trial_payment_method_optional: bool,
          ?trial_period_days: Integer,
          ?zero_amount_payment_method_optional: bool,
          ?type: :recurring_price
        ) -> void

        def to_hash: -> {
          currency: Dodopayments::Models::currency,
          payment_frequency_count: Integer,
          payment_frequency_interval: Dodopayments::Models::time_interval,
          price: Integer,
          subscription_period_count: Integer,
          subscription_period_interval: Dodopayments::Models::time_interval,
          type: :recurring_price,
          discount: Integer,
          discount_bps: Integer?,
          purchasing_power_parity: bool,
          tax_inclusive: bool?,
          trial_amount: Integer?,
          trial_apply_discounts: bool?,
          trial_payment_method_optional: bool,
          trial_period_days: Integer,
          zero_amount_payment_method_optional: bool
        }
      end

      type usage_based_price =
        {
          currency: Dodopayments::Models::currency,
          fixed_price: Integer,
          payment_frequency_count: Integer,
          payment_frequency_interval: Dodopayments::Models::time_interval,
          subscription_period_count: Integer,
          subscription_period_interval: Dodopayments::Models::time_interval,
          type: :usage_based_price,
          discount: Integer,
          discount_bps: Integer?,
          meters: ::Array[Dodopayments::AddMeterToPrice]?,
          purchasing_power_parity: bool,
          tax_inclusive: bool?
        }

      class UsageBasedPrice < Dodopayments::Internal::Type::BaseModel
        attr_accessor currency: Dodopayments::Models::currency

        attr_accessor fixed_price: Integer

        attr_accessor payment_frequency_count: Integer

        attr_accessor payment_frequency_interval: Dodopayments::Models::time_interval

        attr_accessor subscription_period_count: Integer

        attr_accessor subscription_period_interval: Dodopayments::Models::time_interval

        attr_accessor type: :usage_based_price

        attr_reader discount: Integer?

        def discount=: (Integer) -> Integer

        attr_accessor discount_bps: Integer?

        attr_accessor meters: ::Array[Dodopayments::AddMeterToPrice]?

        attr_reader purchasing_power_parity: bool?

        def purchasing_power_parity=: (bool) -> bool

        attr_accessor tax_inclusive: bool?

        def initialize: (
          currency: Dodopayments::Models::currency,
          fixed_price: Integer,
          payment_frequency_count: Integer,
          payment_frequency_interval: Dodopayments::Models::time_interval,
          subscription_period_count: Integer,
          subscription_period_interval: Dodopayments::Models::time_interval,
          ?discount: Integer,
          ?discount_bps: Integer?,
          ?meters: ::Array[Dodopayments::AddMeterToPrice]?,
          ?purchasing_power_parity: bool,
          ?tax_inclusive: bool?,
          ?type: :usage_based_price
        ) -> void

        def to_hash: -> {
          currency: Dodopayments::Models::currency,
          fixed_price: Integer,
          payment_frequency_count: Integer,
          payment_frequency_interval: Dodopayments::Models::time_interval,
          subscription_period_count: Integer,
          subscription_period_interval: Dodopayments::Models::time_interval,
          type: :usage_based_price,
          discount: Integer,
          discount_bps: Integer?,
          meters: ::Array[Dodopayments::AddMeterToPrice]?,
          purchasing_power_parity: bool,
          tax_inclusive: bool?
        }
      end

      def self?.variants: -> ::Array[Dodopayments::Models::price]
    end
  end
end
