module Dodopayments
  module Models
    type product_unarchive_params = {  } & Dodopayments::request_parameters

    class ProductUnarchiveParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      def initialize:
        (request_options: Dodopayments::request_opts) -> void
        | (
          ?Dodopayments::Models::product_unarchive_params
          | Dodopayments::BaseModel data
        ) -> void

      def to_hash: -> Dodopayments::Models::product_unarchive_params
    end
  end
end
