module Dodopayments
  module Models
    type product_list_response =
      {
        business_id: String,
        created_at: Time,
        is_recurring: bool,
        product_id: String,
        tax_category: Dodopayments::Models::ProductListResponse::tax_category,
        updated_at: Time,
        currency: Dodopayments::Models::ProductListResponse::currency?,
        description: String?,
        image: String?,
        name: String?,
        price: Integer?,
        price_detail: Dodopayments::Models::price?,
        tax_inclusive: bool?
      }

    class ProductListResponse < Dodopayments::BaseModel
      attr_accessor business_id: String

      attr_accessor created_at: Time

      attr_accessor is_recurring: bool

      attr_accessor product_id: String

      attr_accessor tax_category: Dodopayments::Models::ProductListResponse::tax_category

      attr_accessor updated_at: Time

      attr_accessor currency: Dodopayments::Models::ProductListResponse::currency?

      attr_accessor description: String?

      attr_accessor image: String?

      attr_accessor name: String?

      attr_accessor price: Integer?

      attr_accessor price_detail: Dodopayments::Models::price?

      attr_accessor tax_inclusive: bool?

      def initialize: (
        business_id: String,
        created_at: Time,
        is_recurring: bool,
        product_id: String,
        tax_category: Dodopayments::Models::ProductListResponse::tax_category,
        updated_at: Time,
        ?currency: Dodopayments::Models::ProductListResponse::currency?,
        ?description: String?,
        ?image: String?,
        ?name: String?,
        ?price: Integer?,
        ?price_detail: Dodopayments::Models::price?,
        ?tax_inclusive: bool?
      ) -> void

      def to_hash: -> Dodopayments::Models::product_list_response

      type tax_category = :digital_products | :saas | :e_book | :edtech

      class TaxCategory < Dodopayments::Enum
        DIGITAL_PRODUCTS: :digital_products
        SAAS: :saas
        E_BOOK: :e_book
        EDTECH: :edtech

        def self.values: -> ::Array[Dodopayments::Models::ProductListResponse::tax_category]
      end

      type currency =
        :AED
        | :ALL
        | :AMD
        | :ANG
        | :AOA
        | :ARS
        | :AUD
        | :AWG
        | :AZN
        | :BAM
        | :BBD
        | :BDT
        | :BGN
        | :BHD
        | :BIF
        | :BMD
        | :BND
        | :BOB
        | :BRL
        | :BSD
        | :BWP
        | :BYN
        | :BZD
        | :CAD
        | :CHF
        | :CLP
        | :CNY
        | :COP
        | :CRC
        | :CUP
        | :CVE
        | :CZK
        | :DJF
        | :DKK
        | :DOP
        | :DZD
        | :EGP
        | :ETB
        | :EUR
        | :FJD
        | :FKP
        | :GBP
        | :GEL
        | :GHS
        | :GIP
        | :GMD
        | :GNF
        | :GTQ
        | :GYD
        | :HKD
        | :HNL
        | :HRK
        | :HTG
        | :HUF
        | :IDR
        | :ILS
        | :INR
        | :IQD
        | :JMD
        | :JOD
        | :JPY
        | :KES
        | :KGS
        | :KHR
        | :KMF
        | :KRW
        | :KWD
        | :KYD
        | :KZT
        | :LAK
        | :LBP
        | :LKR
        | :LRD
        | :LSL
        | :LYD
        | :MAD
        | :MDL
        | :MGA
        | :MKD
        | :MMK
        | :MNT
        | :MOP
        | :MRU
        | :MUR
        | :MVR
        | :MWK
        | :MXN
        | :MYR
        | :MZN
        | :NAD
        | :NGN
        | :NIO
        | :NOK
        | :NPR
        | :NZD
        | :OMR
        | :PAB
        | :PEN
        | :PGK
        | :PHP
        | :PKR
        | :PLN
        | :PYG
        | :QAR
        | :RON
        | :RSD
        | :RUB
        | :RWF
        | :SAR
        | :SBD
        | :SCR
        | :SEK
        | :SGD
        | :SHP
        | :SLE
        | :SLL
        | :SOS
        | :SRD
        | :SSP
        | :STN
        | :SVC
        | :SZL
        | :THB
        | :TND
        | :TOP
        | :TRY
        | :TTD
        | :TWD
        | :TZS
        | :UAH
        | :UGX
        | :USD
        | :UYU
        | :UZS
        | :VES
        | :VND
        | :VUV
        | :WST
        | :XAF
        | :XCD
        | :XOF
        | :XPF
        | :YER
        | :ZAR
        | :ZMW

      class Currency < Dodopayments::Enum
        AED: :AED
        ALL: :ALL
        AMD: :AMD
        ANG: :ANG
        AOA: :AOA
        ARS: :ARS
        AUD: :AUD
        AWG: :AWG
        AZN: :AZN
        BAM: :BAM
        BBD: :BBD
        BDT: :BDT
        BGN: :BGN
        BHD: :BHD
        BIF: :BIF
        BMD: :BMD
        BND: :BND
        BOB: :BOB
        BRL: :BRL
        BSD: :BSD
        BWP: :BWP
        BYN: :BYN
        BZD: :BZD
        CAD: :CAD
        CHF: :CHF
        CLP: :CLP
        CNY: :CNY
        COP: :COP
        CRC: :CRC
        CUP: :CUP
        CVE: :CVE
        CZK: :CZK
        DJF: :DJF
        DKK: :DKK
        DOP: :DOP
        DZD: :DZD
        EGP: :EGP
        ETB: :ETB
        EUR: :EUR
        FJD: :FJD
        FKP: :FKP
        GBP: :GBP
        GEL: :GEL
        GHS: :GHS
        GIP: :GIP
        GMD: :GMD
        GNF: :GNF
        GTQ: :GTQ
        GYD: :GYD
        HKD: :HKD
        HNL: :HNL
        HRK: :HRK
        HTG: :HTG
        HUF: :HUF
        IDR: :IDR
        ILS: :ILS
        INR: :INR
        IQD: :IQD
        JMD: :JMD
        JOD: :JOD
        JPY: :JPY
        KES: :KES
        KGS: :KGS
        KHR: :KHR
        KMF: :KMF
        KRW: :KRW
        KWD: :KWD
        KYD: :KYD
        KZT: :KZT
        LAK: :LAK
        LBP: :LBP
        LKR: :LKR
        LRD: :LRD
        LSL: :LSL
        LYD: :LYD
        MAD: :MAD
        MDL: :MDL
        MGA: :MGA
        MKD: :MKD
        MMK: :MMK
        MNT: :MNT
        MOP: :MOP
        MRU: :MRU
        MUR: :MUR
        MVR: :MVR
        MWK: :MWK
        MXN: :MXN
        MYR: :MYR
        MZN: :MZN
        NAD: :NAD
        NGN: :NGN
        NIO: :NIO
        NOK: :NOK
        NPR: :NPR
        NZD: :NZD
        OMR: :OMR
        PAB: :PAB
        PEN: :PEN
        PGK: :PGK
        PHP: :PHP
        PKR: :PKR
        PLN: :PLN
        PYG: :PYG
        QAR: :QAR
        RON: :RON
        RSD: :RSD
        RUB: :RUB
        RWF: :RWF
        SAR: :SAR
        SBD: :SBD
        SCR: :SCR
        SEK: :SEK
        SGD: :SGD
        SHP: :SHP
        SLE: :SLE
        SLL: :SLL
        SOS: :SOS
        SRD: :SRD
        SSP: :SSP
        STN: :STN
        SVC: :SVC
        SZL: :SZL
        THB: :THB
        TND: :TND
        TOP: :TOP
        TRY: :TRY
        TTD: :TTD
        TWD: :TWD
        TZS: :TZS
        UAH: :UAH
        UGX: :UGX
        USD: :USD
        UYU: :UYU
        UZS: :UZS
        VES: :VES
        VND: :VND
        VUV: :VUV
        WST: :WST
        XAF: :XAF
        XCD: :XCD
        XOF: :XOF
        XPF: :XPF
        YER: :YER
        ZAR: :ZAR
        ZMW: :ZMW

        def self.values: -> ::Array[Dodopayments::Models::ProductListResponse::currency]
      end
    end
  end
end
