module Dodopayments
  module Models
    type product_collection_update_images_params =
      { id: String, force_update: bool? }
      & Dodopayments::Internal::Type::request_parameters

    class ProductCollectionUpdateImagesParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor force_update: bool?

      def initialize: (
        id: String,
        ?force_update: bool?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        force_update: bool?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
