module Dodopayments
  module Models
    type product_collection_update_images_response =
      { url: String, image_id: String? }

    class ProductCollectionUpdateImagesResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor url: String

      attr_accessor image_id: String?

      def initialize: (url: String, ?image_id: String?) -> void

      def to_hash: -> { url: String, image_id: String? }
    end
  end
end
