module Dodopayments
  module Models
    type product_item_req =
      {
        product_id: String,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        amount: Integer?,
        credit_entitlements: ::Array[Dodopayments::ProductItemReq::CreditEntitlement]?
      }

    class ProductItemReq < Dodopayments::Internal::Type::BaseModel
      attr_accessor product_id: String

      attr_accessor quantity: Integer

      attr_accessor addons: ::Array[Dodopayments::AttachAddon]?

      attr_accessor amount: Integer?

      attr_accessor credit_entitlements: ::Array[Dodopayments::ProductItemReq::CreditEntitlement]?

      def initialize: (
        product_id: String,
        quantity: Integer,
        ?addons: ::Array[Dodopayments::AttachAddon]?,
        ?amount: Integer?,
        ?credit_entitlements: ::Array[Dodopayments::ProductItemReq::CreditEntitlement]?
      ) -> void

      def to_hash: -> {
        product_id: String,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        amount: Integer?,
        credit_entitlements: ::Array[Dodopayments::ProductItemReq::CreditEntitlement]?
      }

      type credit_entitlement =
        { credit_entitlement_id: String, credits_amount: String }

      class CreditEntitlement < Dodopayments::Internal::Type::BaseModel
        attr_accessor credit_entitlement_id: String

        attr_accessor credits_amount: String

        def initialize: (
          credit_entitlement_id: String,
          credits_amount: String
        ) -> void

        def to_hash: -> {
          credit_entitlement_id: String,
          credits_amount: String
        }
      end
    end
  end
end
