module Dodopayments
  module Models
    type product_update_params =
      {
        addons: ::Array[String]?,
        brand_id: String?,
        description: String?,
        image_id: String?,
        license_key_activation_message: String?,
        license_key_activations_limit: Integer?,
        license_key_duration: Dodopayments::LicenseKeyDuration?,
        license_key_enabled: bool?,
        name: String?,
        price: Dodopayments::Models::price?,
        tax_category: Dodopayments::Models::tax_category?
      }
      & Dodopayments::Internal::Type::request_parameters

    class ProductUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor addons: ::Array[String]?

      attr_accessor brand_id: String?

      attr_accessor description: String?

      attr_accessor image_id: String?

      attr_accessor license_key_activation_message: String?

      attr_accessor license_key_activations_limit: Integer?

      attr_accessor license_key_duration: Dodopayments::LicenseKeyDuration?

      attr_accessor license_key_enabled: bool?

      attr_accessor name: String?

      attr_accessor price: Dodopayments::Models::price?

      attr_accessor tax_category: Dodopayments::Models::tax_category?

      def initialize: (
        ?addons: ::Array[String]?,
        ?brand_id: String?,
        ?description: String?,
        ?image_id: String?,
        ?license_key_activation_message: String?,
        ?license_key_activations_limit: Integer?,
        ?license_key_duration: Dodopayments::LicenseKeyDuration?,
        ?license_key_enabled: bool?,
        ?name: String?,
        ?price: Dodopayments::Models::price?,
        ?tax_category: Dodopayments::Models::tax_category?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        addons: ::Array[String]?,
        brand_id: String?,
        description: String?,
        image_id: String?,
        license_key_activation_message: String?,
        license_key_activations_limit: Integer?,
        license_key_duration: Dodopayments::LicenseKeyDuration?,
        license_key_enabled: bool?,
        name: String?,
        price: Dodopayments::Models::price?,
        tax_category: Dodopayments::Models::tax_category?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
