module Dodopayments
  module Models
    type product_list_response =
      {
        business_id: String,
        created_at: Time,
        is_recurring: bool,
        product_id: String,
        tax_category: Dodopayments::Models::tax_category,
        updated_at: Time,
        currency: Dodopayments::Models::currency?,
        description: String?,
        image: String?,
        name: String?,
        price: Integer?,
        price_detail: Dodopayments::Models::price?,
        tax_inclusive: bool?
      }

    class ProductListResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor created_at: Time

      attr_accessor is_recurring: bool

      attr_accessor product_id: String

      attr_accessor tax_category: Dodopayments::Models::tax_category

      attr_accessor updated_at: Time

      attr_accessor currency: Dodopayments::Models::currency?

      attr_accessor description: String?

      attr_accessor image: String?

      attr_accessor name: String?

      attr_accessor price: Integer?

      attr_accessor price_detail: Dodopayments::Models::price?

      attr_accessor tax_inclusive: bool?

      def initialize: (
        business_id: String,
        created_at: Time,
        is_recurring: bool,
        product_id: String,
        tax_category: Dodopayments::Models::tax_category,
        updated_at: Time,
        ?currency: Dodopayments::Models::currency?,
        ?description: String?,
        ?image: String?,
        ?name: String?,
        ?price: Integer?,
        ?price_detail: Dodopayments::Models::price?,
        ?tax_inclusive: bool?
      ) -> void
    end
  end
end
