module Dodopayments
  module Models
    type product_collection_list_response =
      {
        id: String,
        created_at: Time,
        name: String,
        products_count: Integer,
        updated_at: Time,
        description: String?,
        image: String?
      }

    class ProductCollectionListResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor name: String

      attr_accessor products_count: Integer

      attr_accessor updated_at: Time

      attr_accessor description: String?

      attr_accessor image: String?

      def initialize: (
        id: String,
        created_at: Time,
        name: String,
        products_count: Integer,
        updated_at: Time,
        ?description: String?,
        ?image: String?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        name: String,
        products_count: Integer,
        updated_at: Time,
        description: String?,
        image: String?
      }
    end
  end
end
