module Dodopayments
  module Models
    type product_delete_params = {  } & Dodopayments::request_parameters

    class ProductDeleteParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> Dodopayments::Models::product_delete_params
    end
  end
end
