module Dodopayments
  module Models
    type product_update_params =
      {
        addons: ::Array[String]?,
        brand_id: String?,
        credit_entitlements: ::Array[Dodopayments::ProductUpdateParams::CreditEntitlement]?,
        description: String?,
        digital_product_delivery: Dodopayments::ProductUpdateParams::DigitalProductDelivery?,
        image_id: String?,
        license_key_activation_message: String?,
        license_key_activations_limit: Integer?,
        license_key_duration: Dodopayments::LicenseKeyDuration?,
        license_key_enabled: bool?,
        metadata: ::Hash[Symbol, String]?,
        name: String?,
        price: Dodopayments::Models::price?,
        tax_category: Dodopayments::Models::tax_category?
      }
      & Dodopayments::Internal::Type::request_parameters

    class ProductUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor addons: ::Array[String]?

      attr_accessor brand_id: String?

      attr_accessor credit_entitlements: ::Array[Dodopayments::ProductUpdateParams::CreditEntitlement]?

      attr_accessor description: String?

      attr_accessor digital_product_delivery: Dodopayments::ProductUpdateParams::DigitalProductDelivery?

      attr_accessor image_id: String?

      attr_accessor license_key_activation_message: String?

      attr_accessor license_key_activations_limit: Integer?

      attr_accessor license_key_duration: Dodopayments::LicenseKeyDuration?

      attr_accessor license_key_enabled: bool?

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_accessor name: String?

      attr_accessor price: Dodopayments::Models::price?

      attr_accessor tax_category: Dodopayments::Models::tax_category?

      def initialize: (
        ?addons: ::Array[String]?,
        ?brand_id: String?,
        ?credit_entitlements: ::Array[Dodopayments::ProductUpdateParams::CreditEntitlement]?,
        ?description: String?,
        ?digital_product_delivery: Dodopayments::ProductUpdateParams::DigitalProductDelivery?,
        ?image_id: String?,
        ?license_key_activation_message: String?,
        ?license_key_activations_limit: Integer?,
        ?license_key_duration: Dodopayments::LicenseKeyDuration?,
        ?license_key_enabled: bool?,
        ?metadata: ::Hash[Symbol, String]?,
        ?name: String?,
        ?price: Dodopayments::Models::price?,
        ?tax_category: Dodopayments::Models::tax_category?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        addons: ::Array[String]?,
        brand_id: String?,
        credit_entitlements: ::Array[Dodopayments::ProductUpdateParams::CreditEntitlement]?,
        description: String?,
        digital_product_delivery: Dodopayments::ProductUpdateParams::DigitalProductDelivery?,
        image_id: String?,
        license_key_activation_message: String?,
        license_key_activations_limit: Integer?,
        license_key_duration: Dodopayments::LicenseKeyDuration?,
        license_key_enabled: bool?,
        metadata: ::Hash[Symbol, String]?,
        name: String?,
        price: Dodopayments::Models::price?,
        tax_category: Dodopayments::Models::tax_category?,
        request_options: Dodopayments::RequestOptions
      }

      type credit_entitlement =
        {
          credit_entitlement_id: String,
          credits_amount: String,
          credits_reduce_overage: bool?,
          currency: Dodopayments::Models::currency?,
          expires_after_days: Integer?,
          low_balance_threshold_percent: Integer?,
          max_rollover_count: Integer?,
          overage_charge_at_billing: bool?,
          overage_enabled: bool?,
          overage_limit: String?,
          preserve_overage_at_reset: bool?,
          price_per_unit: String?,
          proration_behavior: Dodopayments::Models::ProductUpdateParams::CreditEntitlement::proration_behavior?,
          rollover_enabled: bool?,
          rollover_percentage: Integer?,
          rollover_timeframe_count: Integer?,
          rollover_timeframe_interval: Dodopayments::Models::time_interval?,
          trial_credits: String?,
          trial_credits_expire_after_trial: bool?
        }

      class CreditEntitlement < Dodopayments::Internal::Type::BaseModel
        attr_accessor credit_entitlement_id: String

        attr_accessor credits_amount: String

        attr_accessor credits_reduce_overage: bool?

        attr_accessor currency: Dodopayments::Models::currency?

        attr_accessor expires_after_days: Integer?

        attr_accessor low_balance_threshold_percent: Integer?

        attr_accessor max_rollover_count: Integer?

        attr_accessor overage_charge_at_billing: bool?

        attr_accessor overage_enabled: bool?

        attr_accessor overage_limit: String?

        attr_accessor preserve_overage_at_reset: bool?

        attr_accessor price_per_unit: String?

        attr_accessor proration_behavior: Dodopayments::Models::ProductUpdateParams::CreditEntitlement::proration_behavior?

        attr_accessor rollover_enabled: bool?

        attr_accessor rollover_percentage: Integer?

        attr_accessor rollover_timeframe_count: Integer?

        attr_accessor rollover_timeframe_interval: Dodopayments::Models::time_interval?

        attr_accessor trial_credits: String?

        attr_accessor trial_credits_expire_after_trial: bool?

        def initialize: (
          credit_entitlement_id: String,
          credits_amount: String,
          ?credits_reduce_overage: bool?,
          ?currency: Dodopayments::Models::currency?,
          ?expires_after_days: Integer?,
          ?low_balance_threshold_percent: Integer?,
          ?max_rollover_count: Integer?,
          ?overage_charge_at_billing: bool?,
          ?overage_enabled: bool?,
          ?overage_limit: String?,
          ?preserve_overage_at_reset: bool?,
          ?price_per_unit: String?,
          ?proration_behavior: Dodopayments::Models::ProductUpdateParams::CreditEntitlement::proration_behavior?,
          ?rollover_enabled: bool?,
          ?rollover_percentage: Integer?,
          ?rollover_timeframe_count: Integer?,
          ?rollover_timeframe_interval: Dodopayments::Models::time_interval?,
          ?trial_credits: String?,
          ?trial_credits_expire_after_trial: bool?
        ) -> void

        def to_hash: -> {
          credit_entitlement_id: String,
          credits_amount: String,
          credits_reduce_overage: bool?,
          currency: Dodopayments::Models::currency?,
          expires_after_days: Integer?,
          low_balance_threshold_percent: Integer?,
          max_rollover_count: Integer?,
          overage_charge_at_billing: bool?,
          overage_enabled: bool?,
          overage_limit: String?,
          preserve_overage_at_reset: bool?,
          price_per_unit: String?,
          proration_behavior: Dodopayments::Models::ProductUpdateParams::CreditEntitlement::proration_behavior?,
          rollover_enabled: bool?,
          rollover_percentage: Integer?,
          rollover_timeframe_count: Integer?,
          rollover_timeframe_interval: Dodopayments::Models::time_interval?,
          trial_credits: String?,
          trial_credits_expire_after_trial: bool?
        }

        type proration_behavior = :prorate | :no_prorate

        module ProrationBehavior
          extend Dodopayments::Internal::Type::Enum

          PRORATE: :prorate
          NO_PRORATE: :no_prorate

          def self?.values: -> ::Array[Dodopayments::Models::ProductUpdateParams::CreditEntitlement::proration_behavior]
        end
      end

      type digital_product_delivery =
        {
          external_url: String?,
          files: ::Array[String]?,
          instructions: String?
        }

      class DigitalProductDelivery < Dodopayments::Internal::Type::BaseModel
        attr_accessor external_url: String?

        attr_accessor files: ::Array[String]?

        attr_accessor instructions: String?

        def initialize: (
          ?external_url: String?,
          ?files: ::Array[String]?,
          ?instructions: String?
        ) -> void

        def to_hash: -> {
          external_url: String?,
          files: ::Array[String]?,
          instructions: String?
        }
      end
    end
  end
end
