module Dodopayments
  module Models
    type product_collection_create_params =
      {
        groups: ::Array[Dodopayments::ProductCollectionCreateParams::Group],
        name: String,
        brand_id: String?,
        description: String?
      }
      & Dodopayments::Internal::Type::request_parameters

    class ProductCollectionCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor groups: ::Array[Dodopayments::ProductCollectionCreateParams::Group]

      attr_accessor name: String

      attr_accessor brand_id: String?

      attr_accessor description: String?

      def initialize: (
        groups: ::Array[Dodopayments::ProductCollectionCreateParams::Group],
        name: String,
        ?brand_id: String?,
        ?description: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        groups: ::Array[Dodopayments::ProductCollectionCreateParams::Group],
        name: String,
        brand_id: String?,
        description: String?,
        request_options: Dodopayments::RequestOptions
      }

      type group =
        {
          products: ::Array[Dodopayments::ProductCollectionCreateParams::Group::Product],
          group_name: String?,
          status: bool?
        }

      class Group < Dodopayments::Internal::Type::BaseModel
        attr_accessor products: ::Array[Dodopayments::ProductCollectionCreateParams::Group::Product]

        attr_accessor group_name: String?

        attr_accessor status: bool?

        def initialize: (
          products: ::Array[Dodopayments::ProductCollectionCreateParams::Group::Product],
          ?group_name: String?,
          ?status: bool?
        ) -> void

        def to_hash: -> {
          products: ::Array[Dodopayments::ProductCollectionCreateParams::Group::Product],
          group_name: String?,
          status: bool?
        }

        type product = { product_id: String, status: bool? }

        class Product < Dodopayments::Internal::Type::BaseModel
          attr_accessor product_id: String

          attr_accessor status: bool?

          def initialize: (product_id: String, ?status: bool?) -> void

          def to_hash: -> { product_id: String, status: bool? }
        end
      end
    end
  end
end
