module Dodopayments
  module Models
    type refund_list_params =
      {
        created_at_gte: Time?,
        created_at_lte: Time?,
        customer_id: String?,
        page_number: Integer?,
        page_size: Integer?,
        status: Dodopayments::Models::refund_status?
      }
      & Dodopayments::Internal::Type::request_parameters

    class RefundListParams < Dodopayments::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor created_at_gte: Time?

      attr_accessor created_at_lte: Time?

      attr_accessor customer_id: String?

      attr_accessor page_number: Integer?

      attr_accessor page_size: Integer?

      attr_accessor status: Dodopayments::Models::refund_status?

      def initialize: (
        ?created_at_gte: Time?,
        ?created_at_lte: Time?,
        ?customer_id: String?,
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?status: Dodopayments::Models::refund_status?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> Dodopayments::Models::refund_list_params
    end
  end
end
