module Dodopayments
  module Models
    type refund_create_params =
      { payment_id: String, amount: Integer?, reason: String? }
      & Dodopayments::request_parameters

    class RefundCreateParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      attr_accessor payment_id: String

      attr_accessor amount: Integer?

      attr_accessor reason: String?

      def initialize:
        (
          payment_id: String,
          amount: Integer?,
          reason: String?,
          request_options: Dodopayments::request_opts
        ) -> void
        | (
          ?Dodopayments::Models::refund_create_params
          | Dodopayments::BaseModel data
        ) -> void

      def to_hash: -> Dodopayments::Models::refund_create_params
    end
  end
end
