module Dodopayments
  module Models
    type refund_failed_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: Dodopayments::Models::RefundFailedWebhookEvent::type_
      }

    class RefundFailedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Refund

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::RefundFailedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: Dodopayments::Models::RefundFailedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: Dodopayments::Models::RefundFailedWebhookEvent::type_
      }

      type type_ = :"refund.failed"

      module Type
        extend Dodopayments::Internal::Type::Enum

        REFUND_FAILED: :"refund.failed"

        def self?.values: -> ::Array[Dodopayments::Models::RefundFailedWebhookEvent::type_]
      end
    end
  end
end
