module Dodopayments
  module Models
    type refund_create_params =
      { payment_id: String, reason: String? }
      & Dodopayments::Internal::Type::request_parameters

    class RefundCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor payment_id: String

      attr_accessor reason: String?

      def initialize: (
        payment_id: String,
        ?reason: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void
    end
  end
end
