module Dodopayments
  module Models
    type refund_succeeded_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: Dodopayments::Models::RefundSucceededWebhookEvent::type_
      }

    class RefundSucceededWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Refund

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::RefundSucceededWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: Dodopayments::Models::RefundSucceededWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: Dodopayments::Models::RefundSucceededWebhookEvent::type_
      }

      type type_ = :"refund.succeeded"

      module Type
        extend Dodopayments::Internal::Type::Enum

        REFUND_SUCCEEDED: :"refund.succeeded"

        def self?.values: -> ::Array[Dodopayments::Models::RefundSucceededWebhookEvent::type_]
      end
    end
  end
end
