module Dodopayments
  module Models
    type refund =
      {
        business_id: String,
        created_at: Time,
        payment_id: String,
        refund_id: String,
        status: Dodopayments::Models::refund_status,
        amount: Integer?,
        currency: Dodopayments::Models::currency?,
        reason: String?
      }

    class Refund < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor created_at: Time

      attr_accessor payment_id: String

      attr_accessor refund_id: String

      attr_accessor status: Dodopayments::Models::refund_status

      attr_accessor amount: Integer?

      attr_accessor currency: Dodopayments::Models::currency?

      attr_accessor reason: String?

      def initialize: (
        business_id: String,
        created_at: Time,
        payment_id: String,
        refund_id: String,
        status: Dodopayments::Models::refund_status,
        ?amount: Integer?,
        ?currency: Dodopayments::Models::currency?,
        ?reason: String?
      ) -> void
    end
  end
end
