module Dodopayments
  module Models
    type refund_succeeded_webhook_event =
      {
        business_id: String,
        data: Dodopayments::RefundSucceededWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::RefundSucceededWebhookEvent::type_
      }

    class RefundSucceededWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::RefundSucceededWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::RefundSucceededWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::RefundSucceededWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::RefundSucceededWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::RefundSucceededWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::RefundSucceededWebhookEvent::type_
      }

      type data =
        {
          payload_type: Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type
        }

      class Data < Dodopayments::Models::Refund
        def payload_type: -> Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type?

        def payload_type=: (
          Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type _
        ) -> Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type

        def initialize: (
          ?payload_type: Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type
        ) -> void

        def to_hash: -> {
          payload_type: Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type
        }

        type payload_type = :Refund

        module PayloadType
          extend Dodopayments::Internal::Type::Enum

          REFUND: :Refund

          def self?.values: -> ::Array[Dodopayments::Models::RefundSucceededWebhookEvent::Data::payload_type]
        end
      end

      type type_ = :"refund.succeeded"

      module Type
        extend Dodopayments::Internal::Type::Enum

        REFUND_SUCCEEDED: :"refund.succeeded"

        def self?.values: -> ::Array[Dodopayments::Models::RefundSucceededWebhookEvent::type_]
      end
    end
  end
end
