module Dodopayments
  module Models
    type refund_retrieve_params =
      { refund_id: String } & Dodopayments::Internal::Type::request_parameters

    class RefundRetrieveParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor refund_id: String

      def initialize: (
        refund_id: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        refund_id: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
