module Dodopayments
  module Models
    type refund_failed_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: :"refund.failed"
      }

    class RefundFailedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Refund

      attr_accessor timestamp: Time

      attr_accessor type: :"refund.failed"

      def initialize: (
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        ?type: :"refund.failed"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: :"refund.failed"
      }
    end
  end
end
