module Dodopayments
  module Models
    type refund_succeeded_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: :"refund.succeeded"
      }

    class RefundSucceededWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Refund

      attr_accessor timestamp: Time

      attr_accessor type: :"refund.succeeded"

      def initialize: (
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        ?type: :"refund.succeeded"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Refund,
        timestamp: Time,
        type: :"refund.succeeded"
      }
    end
  end
end
