module Dodopayments
  module Models
    type refund_failed_webhook_event =
      {
        business_id: String,
        data: Dodopayments::RefundFailedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::RefundFailedWebhookEvent::type_
      }

    class RefundFailedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::RefundFailedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::RefundFailedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::RefundFailedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::RefundFailedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::RefundFailedWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::RefundFailedWebhookEvent::type_
      }

      type data =
        {
          payload_type: Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type
        }

      class Data < Dodopayments::Models::Refund
        def payload_type: -> Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type?

        def payload_type=: (
          Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type _
        ) -> Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type

        def initialize: (
          ?payload_type: Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type
        ) -> void

        def to_hash: -> {
          payload_type: Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type
        }

        type payload_type = :Refund

        module PayloadType
          extend Dodopayments::Internal::Type::Enum

          REFUND: :Refund

          def self?.values: -> ::Array[Dodopayments::Models::RefundFailedWebhookEvent::Data::payload_type]
        end
      end

      type type_ = :"refund.failed"

      module Type
        extend Dodopayments::Internal::Type::Enum

        REFUND_FAILED: :"refund.failed"

        def self?.values: -> ::Array[Dodopayments::Models::RefundFailedWebhookEvent::type_]
      end
    end
  end
end
