module Dodopayments
  module Models
    type scheduled_plan_change =
      {
        id: String,
        addons: ::Array[Dodopayments::ScheduledPlanChange::Addon],
        created_at: Time,
        effective_at: Time,
        product_id: String,
        quantity: Integer,
        product_description: String?,
        product_name: String?
      }

    class ScheduledPlanChange < Dodopayments::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor addons: ::Array[Dodopayments::ScheduledPlanChange::Addon]

      attr_accessor created_at: Time

      attr_accessor effective_at: Time

      attr_accessor product_id: String

      attr_accessor quantity: Integer

      attr_accessor product_description: String?

      attr_accessor product_name: String?

      def initialize: (
        id: String,
        addons: ::Array[Dodopayments::ScheduledPlanChange::Addon],
        created_at: Time,
        effective_at: Time,
        product_id: String,
        quantity: Integer,
        ?product_description: String?,
        ?product_name: String?
      ) -> void

      def to_hash: -> {
        id: String,
        addons: ::Array[Dodopayments::ScheduledPlanChange::Addon],
        created_at: Time,
        effective_at: Time,
        product_id: String,
        quantity: Integer,
        product_description: String?,
        product_name: String?
      }

      type addon = { addon_id: String, name: String, quantity: Integer }

      class Addon < Dodopayments::Internal::Type::BaseModel
        attr_accessor addon_id: String

        attr_accessor name: String

        attr_accessor quantity: Integer

        def initialize: (
          addon_id: String,
          name: String,
          quantity: Integer
        ) -> void

        def to_hash: -> { addon_id: String, name: String, quantity: Integer }
      end
    end
  end
end
