module Dodopayments
  module Models
    type subscription_create_params =
      {
        billing: Dodopayments::Models::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_id: String,
        quantity: Integer,
        discount_code: String?,
        metadata: ::Hash[Symbol, String],
        payment_link: bool?,
        return_url: String?,
        tax_id: String?,
        trial_period_days: Integer?
      }
      & Dodopayments::request_parameters

    class SubscriptionCreateParams < Dodopayments::BaseModel
      extend Dodopayments::RequestParameters::Converter
      include Dodopayments::RequestParameters

      attr_accessor billing: Dodopayments::Models::BillingAddress

      attr_accessor customer: Dodopayments::Models::customer_request

      attr_accessor product_id: String

      attr_accessor quantity: Integer

      attr_accessor discount_code: String?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_accessor payment_link: bool?

      attr_accessor return_url: String?

      attr_accessor tax_id: String?

      attr_accessor trial_period_days: Integer?

      def initialize:
        (
          billing: Dodopayments::Models::BillingAddress,
          customer: Dodopayments::Models::customer_request,
          product_id: String,
          quantity: Integer,
          ?discount_code: String?,
          ?metadata: ::Hash[Symbol, String],
          ?payment_link: bool?,
          ?return_url: String?,
          ?tax_id: String?,
          ?trial_period_days: Integer?,
          ?request_options: Dodopayments::request_opts
        ) -> void
        | (
          ?Dodopayments::Models::subscription_create_params
          | Dodopayments::BaseModel data
        ) -> void

      def to_hash: -> Dodopayments::Models::subscription_create_params
    end
  end
end
