module Dodopayments
  module Models
    type subscription_active_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionActiveWebhookEvent::type_
      }

    class SubscriptionActiveWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Subscription

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::SubscriptionActiveWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionActiveWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionActiveWebhookEvent::type_
      }

      type type_ = :"subscription.active"

      module Type
        extend Dodopayments::Internal::Type::Enum

        SUBSCRIPTION_ACTIVE: :"subscription.active"

        def self?.values: -> ::Array[Dodopayments::Models::SubscriptionActiveWebhookEvent::type_]
      end
    end
  end
end
