module Dodopayments
  module Models
    type subscription_expired_webhook_event =
      {
        business_id: String,
        data: Dodopayments::SubscriptionExpiredWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_
      }

    class SubscriptionExpiredWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::SubscriptionExpiredWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::SubscriptionExpiredWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::SubscriptionExpiredWebhookEvent::Data,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_
      }

      type data =
        {
          payload_type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type
        }

      class Data < Dodopayments::Models::Subscription
        def payload_type: -> Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type?

        def payload_type=: (
          Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type _
        ) -> Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type

        def initialize: (
          ?payload_type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type
        ) -> void

        def to_hash: -> {
          payload_type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type
        }

        type payload_type = :Subscription

        module PayloadType
          extend Dodopayments::Internal::Type::Enum

          SUBSCRIPTION: :Subscription

          def self?.values: -> ::Array[Dodopayments::Models::SubscriptionExpiredWebhookEvent::Data::payload_type]
        end
      end

      type type_ = :"subscription.expired"

      module Type
        extend Dodopayments::Internal::Type::Enum

        SUBSCRIPTION_EXPIRED: :"subscription.expired"

        def self?.values: -> ::Array[Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_]
      end
    end
  end
end
