module Dodopayments
  module Models
    type subscription_create_params =
      {
        billing: Dodopayments::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_id: String,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        billing_currency: Dodopayments::Models::currency?,
        discount_code: String?,
        :force_3ds => bool?,
        metadata: ::Hash[Symbol, String],
        on_demand: Dodopayments::OnDemandSubscription?,
        one_time_product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?,
        payment_link: bool?,
        payment_method_id: String?,
        redirect_immediately: bool,
        return_url: String?,
        short_link: bool?,
        show_saved_payment_methods: bool,
        tax_id: String?,
        trial_period_days: Integer?
      }
      & Dodopayments::Internal::Type::request_parameters

    class SubscriptionCreateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor billing: Dodopayments::BillingAddress

      attr_accessor customer: Dodopayments::Models::customer_request

      attr_accessor product_id: String

      attr_accessor quantity: Integer

      attr_accessor addons: ::Array[Dodopayments::AttachAddon]?

      attr_accessor allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?

      attr_accessor billing_currency: Dodopayments::Models::currency?

      attr_accessor discount_code: String?

      attr_accessor force_3ds: bool?

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_accessor on_demand: Dodopayments::OnDemandSubscription?

      attr_accessor one_time_product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?

      attr_accessor payment_link: bool?

      attr_accessor payment_method_id: String?

      attr_reader redirect_immediately: bool?

      def redirect_immediately=: (bool) -> bool

      attr_accessor return_url: String?

      attr_accessor short_link: bool?

      attr_reader show_saved_payment_methods: bool?

      def show_saved_payment_methods=: (bool) -> bool

      attr_accessor tax_id: String?

      attr_accessor trial_period_days: Integer?

      def initialize: (
        billing: Dodopayments::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_id: String,
        quantity: Integer,
        ?addons: ::Array[Dodopayments::AttachAddon]?,
        ?allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        ?billing_currency: Dodopayments::Models::currency?,
        ?discount_code: String?,
        ?force_3ds: bool?,
        ?metadata: ::Hash[Symbol, String],
        ?on_demand: Dodopayments::OnDemandSubscription?,
        ?one_time_product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?,
        ?payment_link: bool?,
        ?payment_method_id: String?,
        ?redirect_immediately: bool,
        ?return_url: String?,
        ?short_link: bool?,
        ?show_saved_payment_methods: bool,
        ?tax_id: String?,
        ?trial_period_days: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        billing: Dodopayments::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_id: String,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        billing_currency: Dodopayments::Models::currency?,
        discount_code: String?,
        :force_3ds => bool?,
        metadata: ::Hash[Symbol, String],
        on_demand: Dodopayments::OnDemandSubscription?,
        one_time_product_cart: ::Array[Dodopayments::OneTimeProductCartItem]?,
        payment_link: bool?,
        payment_method_id: String?,
        redirect_immediately: bool,
        return_url: String?,
        short_link: bool?,
        show_saved_payment_methods: bool,
        tax_id: String?,
        trial_period_days: Integer?,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
