module Dodopayments
  module Models
    type subscription_active_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: :"subscription.active"
      }

    class SubscriptionActiveWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Subscription

      attr_accessor timestamp: Time

      attr_accessor type: :"subscription.active"

      def initialize: (
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        ?type: :"subscription.active"
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: :"subscription.active"
      }
    end
  end
end
