module Dodopayments
  module Models
    type subscription_on_hold_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionOnHoldWebhookEvent::type_
      }

    class SubscriptionOnHoldWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Subscription

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::SubscriptionOnHoldWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionOnHoldWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionOnHoldWebhookEvent::type_
      }

      type type_ = :"subscription.on_hold"

      module Type
        extend Dodopayments::Internal::Type::Enum

        SUBSCRIPTION_ON_HOLD: :"subscription.on_hold"

        def self?.values: -> ::Array[Dodopayments::Models::SubscriptionOnHoldWebhookEvent::type_]
      end
    end
  end
end
