module Dodopayments
  module Models
    type subscription_update_params =
      {
        billing: Dodopayments::BillingAddress?,
        cancel_at_next_billing_date: bool?,
        disable_on_demand: Dodopayments::SubscriptionUpdateParams::DisableOnDemand?,
        metadata: ::Hash[Symbol, String]?,
        status: Dodopayments::Models::subscription_status?,
        tax_id: String?
      }
      & Dodopayments::Internal::Type::request_parameters

    class SubscriptionUpdateParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor billing: Dodopayments::BillingAddress?

      attr_accessor cancel_at_next_billing_date: bool?

      attr_accessor disable_on_demand: Dodopayments::SubscriptionUpdateParams::DisableOnDemand?

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_accessor status: Dodopayments::Models::subscription_status?

      attr_accessor tax_id: String?

      def initialize: (
        ?billing: Dodopayments::BillingAddress?,
        ?cancel_at_next_billing_date: bool?,
        ?disable_on_demand: Dodopayments::SubscriptionUpdateParams::DisableOnDemand?,
        ?metadata: ::Hash[Symbol, String]?,
        ?status: Dodopayments::Models::subscription_status?,
        ?tax_id: String?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        billing: Dodopayments::BillingAddress?,
        cancel_at_next_billing_date: bool?,
        disable_on_demand: Dodopayments::SubscriptionUpdateParams::DisableOnDemand?,
        metadata: ::Hash[Symbol, String]?,
        status: Dodopayments::Models::subscription_status?,
        tax_id: String?,
        request_options: Dodopayments::RequestOptions
      }

      type disable_on_demand = { next_billing_date: Time }

      class DisableOnDemand < Dodopayments::Internal::Type::BaseModel
        attr_accessor next_billing_date: Time

        def initialize: (next_billing_date: Time) -> void

        def to_hash: -> { next_billing_date: Time }
      end
    end
  end
end
