module Dodopayments
  module Models
    type subscription =
      {
        addons: ::Array[Dodopayments::AddonCartResponseItem],
        billing: Dodopayments::BillingAddress,
        cancel_at_next_billing_date: bool,
        created_at: Time,
        credit_entitlement_cart: ::Array[Dodopayments::CreditEntitlementCartResponse],
        currency: Dodopayments::Models::currency,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        meter_credit_entitlement_cart: ::Array[Dodopayments::MeterCreditEntitlementCartResponse],
        meters: ::Array[Dodopayments::MeterCartResponseItem],
        next_billing_date: Time,
        on_demand: bool,
        payment_frequency_count: Integer,
        payment_frequency_interval: Dodopayments::Models::time_interval,
        previous_billing_date: Time,
        product_id: String,
        quantity: Integer,
        recurring_pre_tax_amount: Integer,
        status: Dodopayments::Models::subscription_status,
        subscription_id: String,
        subscription_period_count: Integer,
        subscription_period_interval: Dodopayments::Models::time_interval,
        tax_inclusive: bool,
        trial_period_days: Integer,
        cancelled_at: Time?,
        custom_field_responses: ::Array[Dodopayments::CustomFieldResponse]?,
        discount_cycles_remaining: Integer?,
        discount_id: String?,
        expires_at: Time?,
        payment_method_id: String?,
        scheduled_change: Dodopayments::Subscription::ScheduledChange?,
        tax_id: String?
      }

    class Subscription < Dodopayments::Internal::Type::BaseModel
      attr_accessor addons: ::Array[Dodopayments::AddonCartResponseItem]

      attr_accessor billing: Dodopayments::BillingAddress

      attr_accessor cancel_at_next_billing_date: bool

      attr_accessor created_at: Time

      attr_accessor credit_entitlement_cart: ::Array[Dodopayments::CreditEntitlementCartResponse]

      attr_accessor currency: Dodopayments::Models::currency

      attr_accessor customer: Dodopayments::CustomerLimitedDetails

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor meter_credit_entitlement_cart: ::Array[Dodopayments::MeterCreditEntitlementCartResponse]

      attr_accessor meters: ::Array[Dodopayments::MeterCartResponseItem]

      attr_accessor next_billing_date: Time

      attr_accessor on_demand: bool

      attr_accessor payment_frequency_count: Integer

      attr_accessor payment_frequency_interval: Dodopayments::Models::time_interval

      attr_accessor previous_billing_date: Time

      attr_accessor product_id: String

      attr_accessor quantity: Integer

      attr_accessor recurring_pre_tax_amount: Integer

      attr_accessor status: Dodopayments::Models::subscription_status

      attr_accessor subscription_id: String

      attr_accessor subscription_period_count: Integer

      attr_accessor subscription_period_interval: Dodopayments::Models::time_interval

      attr_accessor tax_inclusive: bool

      attr_accessor trial_period_days: Integer

      attr_accessor cancelled_at: Time?

      attr_accessor custom_field_responses: ::Array[Dodopayments::CustomFieldResponse]?

      attr_accessor discount_cycles_remaining: Integer?

      attr_accessor discount_id: String?

      attr_accessor expires_at: Time?

      attr_accessor payment_method_id: String?

      attr_accessor scheduled_change: Dodopayments::Subscription::ScheduledChange?

      attr_accessor tax_id: String?

      def initialize: (
        addons: ::Array[Dodopayments::AddonCartResponseItem],
        billing: Dodopayments::BillingAddress,
        cancel_at_next_billing_date: bool,
        created_at: Time,
        credit_entitlement_cart: ::Array[Dodopayments::CreditEntitlementCartResponse],
        currency: Dodopayments::Models::currency,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        meter_credit_entitlement_cart: ::Array[Dodopayments::MeterCreditEntitlementCartResponse],
        meters: ::Array[Dodopayments::MeterCartResponseItem],
        next_billing_date: Time,
        on_demand: bool,
        payment_frequency_count: Integer,
        payment_frequency_interval: Dodopayments::Models::time_interval,
        previous_billing_date: Time,
        product_id: String,
        quantity: Integer,
        recurring_pre_tax_amount: Integer,
        status: Dodopayments::Models::subscription_status,
        subscription_id: String,
        subscription_period_count: Integer,
        subscription_period_interval: Dodopayments::Models::time_interval,
        tax_inclusive: bool,
        trial_period_days: Integer,
        ?cancelled_at: Time?,
        ?custom_field_responses: ::Array[Dodopayments::CustomFieldResponse]?,
        ?discount_cycles_remaining: Integer?,
        ?discount_id: String?,
        ?expires_at: Time?,
        ?payment_method_id: String?,
        ?scheduled_change: Dodopayments::Subscription::ScheduledChange?,
        ?tax_id: String?
      ) -> void

      def to_hash: -> {
        addons: ::Array[Dodopayments::AddonCartResponseItem],
        billing: Dodopayments::BillingAddress,
        cancel_at_next_billing_date: bool,
        created_at: Time,
        credit_entitlement_cart: ::Array[Dodopayments::CreditEntitlementCartResponse],
        currency: Dodopayments::Models::currency,
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        meter_credit_entitlement_cart: ::Array[Dodopayments::MeterCreditEntitlementCartResponse],
        meters: ::Array[Dodopayments::MeterCartResponseItem],
        next_billing_date: Time,
        on_demand: bool,
        payment_frequency_count: Integer,
        payment_frequency_interval: Dodopayments::Models::time_interval,
        previous_billing_date: Time,
        product_id: String,
        quantity: Integer,
        recurring_pre_tax_amount: Integer,
        status: Dodopayments::Models::subscription_status,
        subscription_id: String,
        subscription_period_count: Integer,
        subscription_period_interval: Dodopayments::Models::time_interval,
        tax_inclusive: bool,
        trial_period_days: Integer,
        cancelled_at: Time?,
        custom_field_responses: ::Array[Dodopayments::CustomFieldResponse]?,
        discount_cycles_remaining: Integer?,
        discount_id: String?,
        expires_at: Time?,
        payment_method_id: String?,
        scheduled_change: Dodopayments::Subscription::ScheduledChange?,
        tax_id: String?
      }

      type scheduled_change =
        {
          id: String,
          addons: ::Array[Dodopayments::Subscription::ScheduledChange::Addon],
          created_at: Time,
          effective_at: Time,
          product_id: String,
          quantity: Integer,
          product_description: String?,
          product_name: String?
        }

      class ScheduledChange < Dodopayments::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor addons: ::Array[Dodopayments::Subscription::ScheduledChange::Addon]

        attr_accessor created_at: Time

        attr_accessor effective_at: Time

        attr_accessor product_id: String

        attr_accessor quantity: Integer

        attr_accessor product_description: String?

        attr_accessor product_name: String?

        def initialize: (
          id: String,
          addons: ::Array[Dodopayments::Subscription::ScheduledChange::Addon],
          created_at: Time,
          effective_at: Time,
          product_id: String,
          quantity: Integer,
          ?product_description: String?,
          ?product_name: String?
        ) -> void

        def to_hash: -> {
          id: String,
          addons: ::Array[Dodopayments::Subscription::ScheduledChange::Addon],
          created_at: Time,
          effective_at: Time,
          product_id: String,
          quantity: Integer,
          product_description: String?,
          product_name: String?
        }

        type addon = { addon_id: String, name: String, quantity: Integer }

        class Addon < Dodopayments::Internal::Type::BaseModel
          attr_accessor addon_id: String

          attr_accessor name: String

          attr_accessor quantity: Integer

          def initialize: (
            addon_id: String,
            name: String,
            quantity: Integer
          ) -> void

          def to_hash: -> { addon_id: String, name: String, quantity: Integer }
        end
      end
    end
  end
end
