module Dodopayments
  module Models
    type subscription_renewed_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionRenewedWebhookEvent::type_
      }

    class SubscriptionRenewedWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Subscription

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::SubscriptionRenewedWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionRenewedWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionRenewedWebhookEvent::type_
      }

      type type_ = :"subscription.renewed"

      module Type
        extend Dodopayments::Internal::Type::Enum

        SUBSCRIPTION_RENEWED: :"subscription.renewed"

        def self?.values: -> ::Array[Dodopayments::Models::SubscriptionRenewedWebhookEvent::type_]
      end
    end
  end
end
