module Dodopayments
  module Models
    type subscription_create_response =
      {
        addons: ::Array[Dodopayments::AddonCartResponseItem],
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        recurring_pre_tax_amount: Integer,
        subscription_id: String,
        client_secret: String?,
        discount_id: String?,
        expires_on: Time?,
        one_time_product_cart: ::Array[Dodopayments::Models::SubscriptionCreateResponse::OneTimeProductCart]?,
        payment_link: String?
      }

    class SubscriptionCreateResponse < Dodopayments::Internal::Type::BaseModel
      attr_accessor addons: ::Array[Dodopayments::AddonCartResponseItem]

      attr_accessor customer: Dodopayments::CustomerLimitedDetails

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor payment_id: String

      attr_accessor recurring_pre_tax_amount: Integer

      attr_accessor subscription_id: String

      attr_accessor client_secret: String?

      attr_accessor discount_id: String?

      attr_accessor expires_on: Time?

      attr_accessor one_time_product_cart: ::Array[Dodopayments::Models::SubscriptionCreateResponse::OneTimeProductCart]?

      attr_accessor payment_link: String?

      def initialize: (
        addons: ::Array[Dodopayments::AddonCartResponseItem],
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        recurring_pre_tax_amount: Integer,
        subscription_id: String,
        ?client_secret: String?,
        ?discount_id: String?,
        ?expires_on: Time?,
        ?one_time_product_cart: ::Array[Dodopayments::Models::SubscriptionCreateResponse::OneTimeProductCart]?,
        ?payment_link: String?
      ) -> void

      def to_hash: -> {
        addons: ::Array[Dodopayments::AddonCartResponseItem],
        customer: Dodopayments::CustomerLimitedDetails,
        metadata: ::Hash[Symbol, String],
        payment_id: String,
        recurring_pre_tax_amount: Integer,
        subscription_id: String,
        client_secret: String?,
        discount_id: String?,
        expires_on: Time?,
        one_time_product_cart: ::Array[Dodopayments::Models::SubscriptionCreateResponse::OneTimeProductCart]?,
        payment_link: String?
      }

      type one_time_product_cart = { product_id: String, quantity: Integer }

      class OneTimeProductCart < Dodopayments::Internal::Type::BaseModel
        attr_accessor product_id: String

        attr_accessor quantity: Integer

        def initialize: (product_id: String, quantity: Integer) -> void

        def to_hash: -> { product_id: String, quantity: Integer }
      end
    end
  end
end
