module Dodopayments
  module Models
    type subscription_expired_webhook_event =
      {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_
      }

    class SubscriptionExpiredWebhookEvent < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Subscription

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_

      def initialize: (
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Subscription,
        timestamp: Time,
        type: Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_
      }

      type type_ = :"subscription.expired"

      module Type
        extend Dodopayments::Internal::Type::Enum

        SUBSCRIPTION_EXPIRED: :"subscription.expired"

        def self?.values: -> ::Array[Dodopayments::Models::SubscriptionExpiredWebhookEvent::type_]
      end
    end
  end
end
