module Dodopayments
  module Models
    type subscription_status =
      :pending | :active | :on_hold | :cancelled | :failed | :expired

    module SubscriptionStatus
      extend Dodopayments::Internal::Type::Enum

      PENDING: :pending
      ACTIVE: :active
      ON_HOLD: :on_hold
      CANCELLED: :cancelled
      FAILED: :failed
      EXPIRED: :expired

      def self?.values: -> ::Array[Dodopayments::Models::subscription_status]
    end
  end
end
