module Dodopayments
  module Models
    type subscription_status =
      :pending
      | :active
      | :on_hold
      | :paused
      | :cancelled
      | :failed
      | :expired
      | :past_due

    module SubscriptionStatus
      extend Dodopayments::Internal::Type::Enum

      PENDING: :pending
      ACTIVE: :active
      ON_HOLD: :on_hold
      PAUSED: :paused
      CANCELLED: :cancelled
      FAILED: :failed
      EXPIRED: :expired
      PAST_DUE: :past_due

      def self?.values: -> ::Array[Dodopayments::Models::subscription_status]
    end
  end
end
