module Dodopayments
  module Models
    type subscription_preview_change_plan_params =
      {
        product_id: String,
        proration_billing_mode: Dodopayments::Models::SubscriptionPreviewChangePlanParams::proration_billing_mode,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        metadata: ::Hash[Symbol, String]?
      }
      & Dodopayments::Internal::Type::request_parameters

    class SubscriptionPreviewChangePlanParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor product_id: String

      attr_accessor proration_billing_mode: Dodopayments::Models::SubscriptionPreviewChangePlanParams::proration_billing_mode

      attr_accessor quantity: Integer

      attr_accessor addons: ::Array[Dodopayments::AttachAddon]?

      attr_accessor metadata: ::Hash[Symbol, String]?

      def initialize: (
        product_id: String,
        proration_billing_mode: Dodopayments::Models::SubscriptionPreviewChangePlanParams::proration_billing_mode,
        quantity: Integer,
        ?addons: ::Array[Dodopayments::AttachAddon]?,
        ?metadata: ::Hash[Symbol, String]?,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        product_id: String,
        proration_billing_mode: Dodopayments::Models::SubscriptionPreviewChangePlanParams::proration_billing_mode,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        metadata: ::Hash[Symbol, String]?,
        request_options: Dodopayments::RequestOptions
      }

      type proration_billing_mode =
        :prorated_immediately | :full_immediately | :difference_immediately

      module ProrationBillingMode
        extend Dodopayments::Internal::Type::Enum

        PRORATED_IMMEDIATELY: :prorated_immediately
        FULL_IMMEDIATELY: :full_immediately
        DIFFERENCE_IMMEDIATELY: :difference_immediately

        def self?.values: -> ::Array[Dodopayments::Models::SubscriptionPreviewChangePlanParams::proration_billing_mode]
      end
    end
  end
end
