module Dodopayments
  module Models
    type subscription_update_payment_method_params =
      {
        subscription_id: String,
        body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body
      }
      & Dodopayments::Internal::Type::request_parameters

    class SubscriptionUpdatePaymentMethodParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor subscription_id: String

      attr_accessor body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body

      def initialize: (
        subscription_id: String,
        body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        subscription_id: String,
        body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body,
        request_options: Dodopayments::RequestOptions
      }

      type body =
        Dodopayments::SubscriptionUpdatePaymentMethodParams::Body::New
        | Dodopayments::SubscriptionUpdatePaymentMethodParams::Body::Existing

      module Body
        extend Dodopayments::Internal::Type::Union

        type new_ =
          {
            type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::New::type_,
            return_url: String?
          }

        class New < Dodopayments::Internal::Type::BaseModel
          attr_accessor type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::New::type_

          attr_accessor return_url: String?

          def initialize: (
            type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::New::type_,
            ?return_url: String?
          ) -> void

          def to_hash: -> {
            type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::New::type_,
            return_url: String?
          }

          type type_ = :new

          module Type
            extend Dodopayments::Internal::Type::Enum

            NEW: :new

            def self?.values: -> ::Array[Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::New::type_]
          end
        end

        type existing =
          {
            payment_method_id: String,
            type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::Existing::type_
          }

        class Existing < Dodopayments::Internal::Type::BaseModel
          attr_accessor payment_method_id: String

          attr_accessor type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::Existing::type_

          def initialize: (
            payment_method_id: String,
            type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::Existing::type_
          ) -> void

          def to_hash: -> {
            payment_method_id: String,
            type: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::Existing::type_
          }

          type type_ = :existing

          module Type
            extend Dodopayments::Internal::Type::Enum

            EXISTING: :existing

            def self?.values: -> ::Array[Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::Body::Existing::type_]
          end
        end

        def self?.variants: -> ::Array[Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body]
      end
    end
  end
end
