module Dodopayments
  module Models
    type subscription_charge_params =
      { product_price: Integer, metadata: ::Hash[Symbol, String]? }
      & Dodopayments::Internal::Type::request_parameters

    class SubscriptionChargeParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor product_price: Integer

      attr_accessor metadata: ::Hash[Symbol, String]?

      def initialize: (
        product_price: Integer,
        ?metadata: ::Hash[Symbol, String]?,
        ?request_options: Dodopayments::request_opts
      ) -> void
    end
  end
end
