module Dodopayments
  module Models
    type subscription_update_payment_method_params =
      {
        subscription_id: String,
        body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body
      }
      & Dodopayments::Internal::Type::request_parameters

    class SubscriptionUpdatePaymentMethodParams < Dodopayments::Internal::Type::BaseModel
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      attr_accessor subscription_id: String

      attr_accessor body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body

      def initialize: (
        subscription_id: String,
        body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        subscription_id: String,
        body: Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body,
        request_options: Dodopayments::RequestOptions
      }

      type body =
        Dodopayments::SubscriptionUpdatePaymentMethodParams::Body::New
        | Dodopayments::SubscriptionUpdatePaymentMethodParams::Body::Existing

      module Body
        extend Dodopayments::Internal::Type::Union

        type new_ = { type: :new, return_url: String? }

        class New < Dodopayments::Internal::Type::BaseModel
          attr_accessor type: :new

          attr_accessor return_url: String?

          def initialize: (?return_url: String?, ?type: :new) -> void

          def to_hash: -> { type: :new, return_url: String? }
        end

        type existing = { payment_method_id: String, type: :existing }

        class Existing < Dodopayments::Internal::Type::BaseModel
          attr_accessor payment_method_id: String

          attr_accessor type: :existing

          def initialize: (payment_method_id: String, ?type: :existing) -> void

          def to_hash: -> { payment_method_id: String, type: :existing }
        end

        def self?.variants: -> ::Array[Dodopayments::Models::SubscriptionUpdatePaymentMethodParams::body]
      end
    end
  end
end
