module Dodopayments
  module Models
    type tax_category =
      :digital_products | :saas | :e_book | :edtech | :live_tutoring

    module TaxCategory
      extend Dodopayments::Internal::Type::Enum

      DIGITAL_PRODUCTS: :digital_products
      SAAS: :saas
      E_BOOK: :e_book
      EDTECH: :edtech
      LIVE_TUTORING: :live_tutoring

      def self?.values: -> ::Array[Dodopayments::Models::tax_category]
    end
  end
end
