module Dodopayments
  module Models
    type time_interval = :Day | :Week | :Month | :Year

    module TimeInterval
      extend Dodopayments::Internal::Type::Enum

      DAY: :Day
      WEEK: :Week
      MONTH: :Month
      YEAR: :Year

      def self?.values: -> ::Array[Dodopayments::Models::time_interval]
    end
  end
end
