module Dodopayments
  module Models
    type unwrap_webhook_event =
      Dodopayments::AbandonedCheckoutDetectedWebhookEvent
      | Dodopayments::AbandonedCheckoutRecoveredWebhookEvent
      | Dodopayments::CreditAddedWebhookEvent
      | Dodopayments::CreditBalanceLowWebhookEvent
      | Dodopayments::CreditDeductedWebhookEvent
      | Dodopayments::CreditExpiredWebhookEvent
      | Dodopayments::CreditManualAdjustmentWebhookEvent
      | Dodopayments::CreditOverageChargedWebhookEvent
      | Dodopayments::CreditOverageResetWebhookEvent
      | Dodopayments::CreditRolledOverWebhookEvent
      | Dodopayments::CreditRolloverForfeitedWebhookEvent
      | Dodopayments::DisputeAcceptedWebhookEvent
      | Dodopayments::DisputeCancelledWebhookEvent
      | Dodopayments::DisputeChallengedWebhookEvent
      | Dodopayments::DisputeExpiredWebhookEvent
      | Dodopayments::DisputeLostWebhookEvent
      | Dodopayments::DisputeOpenedWebhookEvent
      | Dodopayments::DisputeWonWebhookEvent
      | Dodopayments::DunningRecoveredWebhookEvent
      | Dodopayments::DunningStartedWebhookEvent
      | Dodopayments::EntitlementGrantCreatedWebhookEvent
      | Dodopayments::EntitlementGrantDeliveredWebhookEvent
      | Dodopayments::EntitlementGrantFailedWebhookEvent
      | Dodopayments::EntitlementGrantRevokedWebhookEvent
      | Dodopayments::LicenseKeyCreatedWebhookEvent
      | Dodopayments::PaymentCancelledWebhookEvent
      | Dodopayments::PaymentFailedWebhookEvent
      | Dodopayments::PaymentProcessingWebhookEvent
      | Dodopayments::PaymentSucceededWebhookEvent
      | Dodopayments::RefundFailedWebhookEvent
      | Dodopayments::RefundSucceededWebhookEvent
      | Dodopayments::SubscriptionActiveWebhookEvent
      | Dodopayments::SubscriptionCancelledWebhookEvent
      | Dodopayments::SubscriptionExpiredWebhookEvent
      | Dodopayments::SubscriptionFailedWebhookEvent
      | Dodopayments::SubscriptionOnHoldWebhookEvent
      | Dodopayments::SubscriptionPlanChangedWebhookEvent
      | Dodopayments::SubscriptionRenewedWebhookEvent
      | Dodopayments::SubscriptionUpdatedWebhookEvent

    module UnwrapWebhookEvent
      extend Dodopayments::Internal::Type::Union

      def self?.variants: -> ::Array[Dodopayments::Models::unwrap_webhook_event]
    end
  end
end
