module Dodopayments
  module Models
    type update_subscription_plan_req =
      {
        product_id: String,
        proration_billing_mode: Dodopayments::Models::UpdateSubscriptionPlanReq::proration_billing_mode,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        discount_code: String?,
        effective_at: Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at,
        metadata: ::Hash[Symbol, String]?,
        on_payment_failure: Dodopayments::Models::UpdateSubscriptionPlanReq::on_payment_failure?
      }

    class UpdateSubscriptionPlanReq < Dodopayments::Internal::Type::BaseModel
      attr_accessor product_id: String

      attr_accessor proration_billing_mode: Dodopayments::Models::UpdateSubscriptionPlanReq::proration_billing_mode

      attr_accessor quantity: Integer

      attr_accessor addons: ::Array[Dodopayments::AttachAddon]?

      attr_accessor discount_code: String?

      attr_reader effective_at: Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at?

      def effective_at=: (
        Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at
      ) -> Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_accessor on_payment_failure: Dodopayments::Models::UpdateSubscriptionPlanReq::on_payment_failure?

      def initialize: (
        product_id: String,
        proration_billing_mode: Dodopayments::Models::UpdateSubscriptionPlanReq::proration_billing_mode,
        quantity: Integer,
        ?addons: ::Array[Dodopayments::AttachAddon]?,
        ?discount_code: String?,
        ?effective_at: Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at,
        ?metadata: ::Hash[Symbol, String]?,
        ?on_payment_failure: Dodopayments::Models::UpdateSubscriptionPlanReq::on_payment_failure?
      ) -> void

      def to_hash: -> {
        product_id: String,
        proration_billing_mode: Dodopayments::Models::UpdateSubscriptionPlanReq::proration_billing_mode,
        quantity: Integer,
        addons: ::Array[Dodopayments::AttachAddon]?,
        discount_code: String?,
        effective_at: Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at,
        metadata: ::Hash[Symbol, String]?,
        on_payment_failure: Dodopayments::Models::UpdateSubscriptionPlanReq::on_payment_failure?
      }

      type proration_billing_mode =
        :prorated_immediately
        | :full_immediately
        | :difference_immediately
        | :do_not_bill

      module ProrationBillingMode
        extend Dodopayments::Internal::Type::Enum

        PRORATED_IMMEDIATELY: :prorated_immediately
        FULL_IMMEDIATELY: :full_immediately
        DIFFERENCE_IMMEDIATELY: :difference_immediately
        DO_NOT_BILL: :do_not_bill

        def self?.values: -> ::Array[Dodopayments::Models::UpdateSubscriptionPlanReq::proration_billing_mode]
      end

      type effective_at = :immediately | :next_billing_date

      module EffectiveAt
        extend Dodopayments::Internal::Type::Enum

        IMMEDIATELY: :immediately
        NEXT_BILLING_DATE: :next_billing_date

        def self?.values: -> ::Array[Dodopayments::Models::UpdateSubscriptionPlanReq::effective_at]
      end

      type on_payment_failure = :prevent_change | :apply_change

      module OnPaymentFailure
        extend Dodopayments::Internal::Type::Enum

        PREVENT_CHANGE: :prevent_change
        APPLY_CHANGE: :apply_change

        def self?.values: -> ::Array[Dodopayments::Models::UpdateSubscriptionPlanReq::on_payment_failure]
      end
    end
  end
end
