module Dodopayments
  module Models
    type webhook_payload =
      {
        business_id: String,
        data: Dodopayments::Models::WebhookPayload::data,
        timestamp: Time,
        type: Dodopayments::Models::webhook_event_type
      }

    class WebhookPayload < Dodopayments::Internal::Type::BaseModel
      attr_accessor business_id: String

      attr_accessor data: Dodopayments::Models::WebhookPayload::data

      attr_accessor timestamp: Time

      attr_accessor type: Dodopayments::Models::webhook_event_type

      def initialize: (
        business_id: String,
        data: Dodopayments::Models::WebhookPayload::data,
        timestamp: Time,
        type: Dodopayments::Models::webhook_event_type
      ) -> void

      def to_hash: -> {
        business_id: String,
        data: Dodopayments::Models::WebhookPayload::data,
        timestamp: Time,
        type: Dodopayments::Models::webhook_event_type
      }

      type data =
        Dodopayments::WebhookPayload::Data::Payment
        | Dodopayments::WebhookPayload::Data::Subscription
        | Dodopayments::WebhookPayload::Data::Refund
        | Dodopayments::WebhookPayload::Data::Dispute
        | Dodopayments::WebhookPayload::Data::LicenseKey
        | Dodopayments::WebhookPayload::Data::CreditLedgerEntry
        | Dodopayments::WebhookPayload::Data::CreditBalanceLow
        | Dodopayments::WebhookPayload::Data::AbandonedCheckout
        | Dodopayments::WebhookPayload::Data::DunningAttempt
        | Dodopayments::WebhookPayload::Data::EntitlementGrant

      module Data
        extend Dodopayments::Internal::Type::Union

        type payment =
          {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Payment::payload_type
          }

        class Payment < Dodopayments::Models::Payment
          def payload_type: -> Dodopayments::Models::WebhookPayload::Data::Payment::payload_type

          def payload_type=: (
            Dodopayments::Models::WebhookPayload::Data::Payment::payload_type _
          ) -> Dodopayments::Models::WebhookPayload::Data::Payment::payload_type

          def initialize: (
            payload_type: Dodopayments::Models::WebhookPayload::Data::Payment::payload_type
          ) -> void

          def to_hash: -> {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Payment::payload_type
          }

          type payload_type = :Payment

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            PAYMENT: :Payment

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::Payment::payload_type]
          end
        end

        type subscription =
          {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type
          }

        class Subscription < Dodopayments::Models::Subscription
          def payload_type: -> Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type

          def payload_type=: (
            Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type _
          ) -> Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type

          def initialize: (
            payload_type: Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type
          ) -> void

          def to_hash: -> {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type
          }

          type payload_type = :Subscription

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            SUBSCRIPTION: :Subscription

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::Subscription::payload_type]
          end
        end

        type refund =
          {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Refund::payload_type
          }

        class Refund < Dodopayments::Models::Refund
          def payload_type: -> Dodopayments::Models::WebhookPayload::Data::Refund::payload_type

          def payload_type=: (
            Dodopayments::Models::WebhookPayload::Data::Refund::payload_type _
          ) -> Dodopayments::Models::WebhookPayload::Data::Refund::payload_type

          def initialize: (
            payload_type: Dodopayments::Models::WebhookPayload::Data::Refund::payload_type
          ) -> void

          def to_hash: -> {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Refund::payload_type
          }

          type payload_type = :Refund

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            REFUND: :Refund

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::Refund::payload_type]
          end
        end

        type dispute =
          {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type
          }

        class Dispute < Dodopayments::Models::GetDispute
          def payload_type: -> Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type

          def payload_type=: (
            Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type _
          ) -> Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type

          def initialize: (
            payload_type: Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type
          ) -> void

          def to_hash: -> {
            payload_type: Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type
          }

          type payload_type = :Dispute

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            DISPUTE: :Dispute

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::Dispute::payload_type]
          end
        end

        type license_key =
          {
            payload_type: Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type
          }

        class LicenseKey < Dodopayments::Models::LicenseKey
          def payload_type: -> Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type

          def payload_type=: (
            Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type _
          ) -> Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type

          def initialize: (
            payload_type: Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type
          ) -> void

          def to_hash: -> {
            payload_type: Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type
          }

          type payload_type = :LicenseKey

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            LICENSE_KEY: :LicenseKey

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::LicenseKey::payload_type]
          end
        end

        type credit_ledger_entry =
          {
            payload_type: Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type
          }

        class CreditLedgerEntry < Dodopayments::Models::CreditEntitlements::CreditLedgerEntry
          def payload_type: -> Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type

          def payload_type=: (
            Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type _
          ) -> Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type

          def initialize: (
            payload_type: Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type
          ) -> void

          def to_hash: -> {
            payload_type: Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type
          }

          type payload_type = :CreditLedgerEntry

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            CREDIT_LEDGER_ENTRY: :CreditLedgerEntry

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::CreditLedgerEntry::payload_type]
          end
        end

        type credit_balance_low =
          {
            available_balance: String,
            credit_entitlement_id: String,
            credit_entitlement_name: String,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::CreditBalanceLow::payload_type,
            subscription_credits_amount: String,
            subscription_id: String,
            threshold_amount: String,
            threshold_percent: Integer
          }

        class CreditBalanceLow < Dodopayments::Internal::Type::BaseModel
          attr_accessor available_balance: String

          attr_accessor credit_entitlement_id: String

          attr_accessor credit_entitlement_name: String

          attr_accessor customer_id: String

          attr_accessor payload_type: Dodopayments::Models::WebhookPayload::Data::CreditBalanceLow::payload_type

          attr_accessor subscription_credits_amount: String

          attr_accessor subscription_id: String

          attr_accessor threshold_amount: String

          attr_accessor threshold_percent: Integer

          def initialize: (
            available_balance: String,
            credit_entitlement_id: String,
            credit_entitlement_name: String,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::CreditBalanceLow::payload_type,
            subscription_credits_amount: String,
            subscription_id: String,
            threshold_amount: String,
            threshold_percent: Integer
          ) -> void

          def to_hash: -> {
            available_balance: String,
            credit_entitlement_id: String,
            credit_entitlement_name: String,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::CreditBalanceLow::payload_type,
            subscription_credits_amount: String,
            subscription_id: String,
            threshold_amount: String,
            threshold_percent: Integer
          }

          type payload_type = :CreditBalanceLow

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            CREDIT_BALANCE_LOW: :CreditBalanceLow

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::CreditBalanceLow::payload_type]
          end
        end

        type abandoned_checkout =
          {
            abandoned_at: Time,
            abandonment_reason: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::abandonment_reason,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::payload_type,
            payment_id: String,
            status: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::status,
            recovered_payment_id: String?
          }

        class AbandonedCheckout < Dodopayments::Internal::Type::BaseModel
          attr_accessor abandoned_at: Time

          attr_accessor abandonment_reason: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::abandonment_reason

          attr_accessor customer_id: String

          attr_accessor payload_type: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::payload_type

          attr_accessor payment_id: String

          attr_accessor status: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::status

          attr_accessor recovered_payment_id: String?

          def initialize: (
            abandoned_at: Time,
            abandonment_reason: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::abandonment_reason,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::payload_type,
            payment_id: String,
            status: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::status,
            ?recovered_payment_id: String?
          ) -> void

          def to_hash: -> {
            abandoned_at: Time,
            abandonment_reason: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::abandonment_reason,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::payload_type,
            payment_id: String,
            status: Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::status,
            recovered_payment_id: String?
          }

          type abandonment_reason = :payment_failed | :checkout_incomplete

          module AbandonmentReason
            extend Dodopayments::Internal::Type::Enum

            PAYMENT_FAILED: :payment_failed
            CHECKOUT_INCOMPLETE: :checkout_incomplete

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::abandonment_reason]
          end

          type payload_type = :AbandonedCheckout

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            ABANDONED_CHECKOUT: :AbandonedCheckout

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::payload_type]
          end

          type status =
            :abandoned | :recovering | :recovered | :exhausted | :opted_out

          module Status
            extend Dodopayments::Internal::Type::Enum

            ABANDONED: :abandoned
            RECOVERING: :recovering
            RECOVERED: :recovered
            EXHAUSTED: :exhausted
            OPTED_OUT: :opted_out

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::AbandonedCheckout::status]
          end
        end

        type dunning_attempt =
          {
            created_at: Time,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::payload_type,
            status: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::status,
            subscription_id: String,
            trigger_state: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::trigger_state,
            payment_id: String?
          }

        class DunningAttempt < Dodopayments::Internal::Type::BaseModel
          attr_accessor created_at: Time

          attr_accessor customer_id: String

          attr_accessor payload_type: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::payload_type

          attr_accessor status: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::status

          attr_accessor subscription_id: String

          attr_accessor trigger_state: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::trigger_state

          attr_accessor payment_id: String?

          def initialize: (
            created_at: Time,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::payload_type,
            status: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::status,
            subscription_id: String,
            trigger_state: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::trigger_state,
            ?payment_id: String?
          ) -> void

          def to_hash: -> {
            created_at: Time,
            customer_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::payload_type,
            status: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::status,
            subscription_id: String,
            trigger_state: Dodopayments::Models::WebhookPayload::Data::DunningAttempt::trigger_state,
            payment_id: String?
          }

          type payload_type = :DunningAttempt

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            DUNNING_ATTEMPT: :DunningAttempt

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::DunningAttempt::payload_type]
          end

          type status = :recovering | :recovered | :exhausted

          module Status
            extend Dodopayments::Internal::Type::Enum

            RECOVERING: :recovering
            RECOVERED: :recovered
            EXHAUSTED: :exhausted

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::DunningAttempt::status]
          end

          type trigger_state = :on_hold | :cancelled

          module TriggerState
            extend Dodopayments::Internal::Type::Enum

            ON_HOLD: :on_hold
            CANCELLED: :cancelled

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::DunningAttempt::trigger_state]
          end
        end

        type entitlement_grant =
          {
            id: String,
            business_id: String,
            created_at: Time,
            customer_id: String,
            entitlement_id: String,
            external_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::payload_type,
            status: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::status,
            updated_at: Time,
            delivered_at: Time?,
            digital_product_delivery: Dodopayments::DigitalProductDelivery?,
            error_code: String?,
            error_message: String?,
            license_key: Dodopayments::WebhookPayload::Data::EntitlementGrant::LicenseKey?,
            metadata: top,
            oauth_expires_at: Time?,
            oauth_url: String?,
            payment_id: String?,
            revocation_reason: String?,
            revoked_at: Time?,
            subscription_id: String?
          }

        class EntitlementGrant < Dodopayments::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor business_id: String

          attr_accessor created_at: Time

          attr_accessor customer_id: String

          attr_accessor entitlement_id: String

          attr_accessor external_id: String

          attr_accessor payload_type: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::payload_type

          attr_accessor status: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::status

          attr_accessor updated_at: Time

          attr_accessor delivered_at: Time?

          attr_accessor digital_product_delivery: Dodopayments::DigitalProductDelivery?

          attr_accessor error_code: String?

          attr_accessor error_message: String?

          attr_accessor license_key: Dodopayments::WebhookPayload::Data::EntitlementGrant::LicenseKey?

          attr_reader metadata: top?

          def metadata=: (top) -> top

          attr_accessor oauth_expires_at: Time?

          attr_accessor oauth_url: String?

          attr_accessor payment_id: String?

          attr_accessor revocation_reason: String?

          attr_accessor revoked_at: Time?

          attr_accessor subscription_id: String?

          def initialize: (
            id: String,
            business_id: String,
            created_at: Time,
            customer_id: String,
            entitlement_id: String,
            external_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::payload_type,
            status: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::status,
            updated_at: Time,
            ?delivered_at: Time?,
            ?digital_product_delivery: Dodopayments::DigitalProductDelivery?,
            ?error_code: String?,
            ?error_message: String?,
            ?license_key: Dodopayments::WebhookPayload::Data::EntitlementGrant::LicenseKey?,
            ?metadata: top,
            ?oauth_expires_at: Time?,
            ?oauth_url: String?,
            ?payment_id: String?,
            ?revocation_reason: String?,
            ?revoked_at: Time?,
            ?subscription_id: String?
          ) -> void

          def to_hash: -> {
            id: String,
            business_id: String,
            created_at: Time,
            customer_id: String,
            entitlement_id: String,
            external_id: String,
            payload_type: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::payload_type,
            status: Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::status,
            updated_at: Time,
            delivered_at: Time?,
            digital_product_delivery: Dodopayments::DigitalProductDelivery?,
            error_code: String?,
            error_message: String?,
            license_key: Dodopayments::WebhookPayload::Data::EntitlementGrant::LicenseKey?,
            metadata: top,
            oauth_expires_at: Time?,
            oauth_url: String?,
            payment_id: String?,
            revocation_reason: String?,
            revoked_at: Time?,
            subscription_id: String?
          }

          type payload_type = :EntitlementGrant

          module PayloadType
            extend Dodopayments::Internal::Type::Enum

            ENTITLEMENT_GRANT: :EntitlementGrant

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::payload_type]
          end

          type status = :Pending | :Delivered | :Failed | :Revoked

          module Status
            extend Dodopayments::Internal::Type::Enum

            PENDING: :Pending
            DELIVERED: :Delivered
            FAILED: :Failed
            REVOKED: :Revoked

            def self?.values: -> ::Array[Dodopayments::Models::WebhookPayload::Data::EntitlementGrant::status]
          end

          type license_key =
            {
              activations_used: Integer,
              key: String,
              activations_limit: Integer?,
              expires_at: Time?
            }

          class LicenseKey < Dodopayments::Internal::Type::BaseModel
            attr_accessor activations_used: Integer

            attr_accessor key: String

            attr_accessor activations_limit: Integer?

            attr_accessor expires_at: Time?

            def initialize: (
              activations_used: Integer,
              key: String,
              ?activations_limit: Integer?,
              ?expires_at: Time?
            ) -> void

            def to_hash: -> {
              activations_used: Integer,
              key: String,
              activations_limit: Integer?,
              expires_at: Time?
            }
          end
        end

        def self?.variants: -> ::Array[Dodopayments::Models::WebhookPayload::data]
      end
    end
  end
end
