module Dodopayments
  module Models
    type webhook_event_retrieve_params = {  } & Dodopayments::request_parameters

    class WebhookEventRetrieveParams < Dodopayments::BaseModel
      extend Dodopayments::Type::RequestParameters::Converter
      include Dodopayments::RequestParameters

      def initialize: (?request_options: Dodopayments::request_opts) -> void

      def to_hash: -> Dodopayments::Models::webhook_event_retrieve_params
    end
  end
end
