module Dodopayments
  module Models
    type your_webhook_url_create_params =
      {
        webhook_id: String,
        webhook_signature: String,
        webhook_timestamp: String
      }
      & Dodopayments::Internal::Type::request_parameters

    class YourWebhookURLCreateParams < Dodopayments::Models::WebhookPayload
      extend Dodopayments::Internal::Type::RequestParameters::Converter
      include Dodopayments::Internal::Type::RequestParameters

      def webhook_id: -> String

      def webhook_id=: (String _) -> String

      def webhook_signature: -> String

      def webhook_signature=: (String _) -> String

      def webhook_timestamp: -> String

      def webhook_timestamp=: (String _) -> String

      def initialize: (
        webhook_id: String,
        webhook_signature: String,
        webhook_timestamp: String,
        ?request_options: Dodopayments::request_opts
      ) -> void

      def to_hash: -> {
        webhook_id: String,
        webhook_signature: String,
        webhook_timestamp: String,
        request_options: Dodopayments::RequestOptions
      }
    end
  end
end
