module Dodopayments
  module Models
    module CreditEntitlements
      type balance_list_grants_response =
        {
          id: String,
          created_at: Time,
          credit_entitlement_id: String,
          customer_id: String,
          initial_amount: String,
          is_expired: bool,
          is_rolled_over: bool,
          remaining_amount: String,
          rollover_count: Integer,
          source_type: Dodopayments::Models::CreditEntitlements::BalanceListGrantsResponse::source_type,
          updated_at: Time,
          expires_at: Time?,
          metadata: ::Hash[Symbol, String]?,
          parent_grant_id: String?,
          source_id: String?
        }

      class BalanceListGrantsResponse < Dodopayments::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor credit_entitlement_id: String

        attr_accessor customer_id: String

        attr_accessor initial_amount: String

        attr_accessor is_expired: bool

        attr_accessor is_rolled_over: bool

        attr_accessor remaining_amount: String

        attr_accessor rollover_count: Integer

        attr_accessor source_type: Dodopayments::Models::CreditEntitlements::BalanceListGrantsResponse::source_type

        attr_accessor updated_at: Time

        attr_accessor expires_at: Time?

        attr_accessor metadata: ::Hash[Symbol, String]?

        attr_accessor parent_grant_id: String?

        attr_accessor source_id: String?

        def initialize: (
          id: String,
          created_at: Time,
          credit_entitlement_id: String,
          customer_id: String,
          initial_amount: String,
          is_expired: bool,
          is_rolled_over: bool,
          remaining_amount: String,
          rollover_count: Integer,
          source_type: Dodopayments::Models::CreditEntitlements::BalanceListGrantsResponse::source_type,
          updated_at: Time,
          ?expires_at: Time?,
          ?metadata: ::Hash[Symbol, String]?,
          ?parent_grant_id: String?,
          ?source_id: String?
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          credit_entitlement_id: String,
          customer_id: String,
          initial_amount: String,
          is_expired: bool,
          is_rolled_over: bool,
          remaining_amount: String,
          rollover_count: Integer,
          source_type: Dodopayments::Models::CreditEntitlements::BalanceListGrantsResponse::source_type,
          updated_at: Time,
          expires_at: Time?,
          metadata: ::Hash[Symbol, String]?,
          parent_grant_id: String?,
          source_id: String?
        }

        type source_type = :subscription | :one_time | :addon | :api | :rollover

        module SourceType
          extend Dodopayments::Internal::Type::Enum

          SUBSCRIPTION: :subscription
          ONE_TIME: :one_time
          ADDON: :addon
          API: :api
          ROLLOVER: :rollover

          def self?.values: -> ::Array[Dodopayments::Models::CreditEntitlements::BalanceListGrantsResponse::source_type]
        end
      end
    end
  end
end
