module Dodopayments
  module Resources
    class Customers
      attr_reader customer_portal: Dodopayments::Resources::Customers::CustomerPortal

      def create: (
        email: String,
        name: String,
        ?phone_number: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::Customer

      def retrieve: (
        String customer_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::Customer

      def update: (
        String customer_id,
        ?name: String?,
        ?phone_number: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::Customer

      def list: (
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::DefaultPageNumberPagination[Dodopayments::Models::Customer]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
