module Dodopayments
  module Resources
    class Customers
      attr_reader customer_portal: Dodopayments::Resources::Customers::CustomerPortal

      attr_reader wallets: Dodopayments::Resources::Customers::Wallets

      def create: (
        email: String,
        name: String,
        ?metadata: ::Hash[Symbol, String],
        ?phone_number: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Customer

      def retrieve: (
        String customer_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Customer

      def update: (
        String customer_id,
        ?metadata: ::Hash[Symbol, String]?,
        ?name: String?,
        ?phone_number: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Customer

      def list: (
        ?email: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Customer]

      def retrieve_payment_methods: (
        String customer_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::CustomerRetrievePaymentMethodsResponse

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
