module Dodopayments
  module Resources
    class Discounts
      def create: (
        amount: Integer,
        type: Dodopayments::Models::discount_type,
        ?code: String?,
        ?expires_at: Time?,
        ?name: String?,
        ?restricted_to: ::Array[String]?,
        ?subscription_cycles: Integer?,
        ?usage_limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Discount

      def retrieve: (
        String discount_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Discount

      def update: (
        String discount_id,
        ?amount: Integer?,
        ?code: String?,
        ?expires_at: Time?,
        ?name: String?,
        ?restricted_to: ::Array[String]?,
        ?subscription_cycles: Integer?,
        ?type: Dodopayments::Models::discount_type?,
        ?usage_limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Discount

      def list: (
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Discount]

      def delete: (
        String discount_id,
        ?request_options: Dodopayments::request_opts
      ) -> nil

      def retrieve_by_code: (
        String code,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Discount

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
