module Dodopayments
  module Resources
    class Licenses
      def activate: (
        license_key: String,
        name: String,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::LicenseKeyInstance

      def deactivate: (
        license_key: String,
        license_key_instance_id: String,
        ?request_options: Dodopayments::request_opts
      ) -> nil

      def validate: (
        license_key: String,
        ?license_key_instance_id: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::LicenseValidateResponse

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
