module Dodopayments
  module Resources
    class LicenseKeys
      def retrieve: (
        String id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::LicenseKey

      def update: (
        String id,
        ?activations_limit: Integer?,
        ?disabled: bool?,
        ?expires_at: Time?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::LicenseKey

      def list: (
        ?customer_id: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?product_id: String,
        ?status: Dodopayments::Models::LicenseKeyListParams::status,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::license_key_list_response

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
