module Dodopayments
  module Resources
    class LicenseKeyInstances
      def retrieve: (
        String id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::LicenseKeyInstance

      def update: (
        String id,
        name: String,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::LicenseKeyInstance

      def list: (
        ?license_key_id: String?,
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::LicenseKeyInstance]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
