module Dodopayments
  module Resources
    class Payments
      def create: (
        billing: Dodopayments::Models::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_cart: ::Array[Dodopayments::Models::OneTimeProductCartItem],
        ?allowed_payment_method_types: ::Array[Dodopayments::Models::PaymentCreateParams::allowed_payment_method_type]?,
        ?discount_code: String?,
        ?metadata: ::Hash[Symbol, String],
        ?payment_link: bool?,
        ?return_url: String?,
        ?tax_id: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::PaymentCreateResponse

      def retrieve: (
        String payment_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::Payment

      def list: (
        ?created_at_gte: Time?,
        ?created_at_lte: Time?,
        ?customer_id: String?,
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?status: Dodopayments::Models::intent_status?,
        ?subscription_id: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::DefaultPageNumberPagination[Dodopayments::Models::PaymentListResponse]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
