module Dodopayments
  module Resources
    class Payments
      def create:
        (
          Dodopayments::Models::PaymentCreateParams | ::Hash[Symbol, top] params
        ) -> Dodopayments::Models::PaymentCreateResponse
        | (
          billing: Dodopayments::Models::BillingAddress,
          customer: Dodopayments::Models::customer_request,
          product_cart: ::Array[Dodopayments::Models::OneTimeProductCartItem],
          discount_code: String?,
          metadata: ::Hash[Symbol, String],
          payment_link: bool?,
          return_url: String?,
          tax_id: String?,
          request_options: Dodopayments::request_opts
        ) -> Dodopayments::Models::PaymentCreateResponse

      def retrieve:
        (
          String payment_id,
          ?Dodopayments::Models::PaymentRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Dodopayments::Models::Payment
        | (
          String payment_id,
          request_options: Dodopayments::request_opts
        ) -> Dodopayments::Models::Payment

      def list:
        (
          ?Dodopayments::Models::PaymentListParams | ::Hash[Symbol, top] params
        ) -> Dodopayments::DefaultPageNumberPagination[Dodopayments::Models::PaymentListResponse]
        | (
          created_at_gte: Time?,
          created_at_lte: Time?,
          customer_id: String?,
          page_number: Integer?,
          page_size: Integer?,
          status: Dodopayments::Models::intent_status?,
          subscription_id: String?,
          request_options: Dodopayments::request_opts
        ) -> Dodopayments::DefaultPageNumberPagination[Dodopayments::Models::PaymentListResponse]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
