module Dodopayments
  module Resources
    class Payments
      def create: (
        billing: Dodopayments::BillingAddress,
        customer: Dodopayments::Models::customer_request,
        product_cart: ::Array[Dodopayments::OneTimeProductCartItem],
        ?allowed_payment_method_types: ::Array[Dodopayments::Models::payment_method_types]?,
        ?billing_currency: Dodopayments::Models::currency?,
        ?discount_code: String?,
        ?metadata: ::Hash[Symbol, String],
        ?payment_link: bool?,
        ?return_url: String?,
        ?show_saved_payment_methods: bool,
        ?tax_id: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::PaymentCreateResponse

      def retrieve: (
        String payment_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Payment

      def list: (
        ?brand_id: String,
        ?created_at_gte: Time,
        ?created_at_lte: Time,
        ?customer_id: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?status: Dodopayments::Models::PaymentListParams::status,
        ?subscription_id: String,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Models::PaymentListResponse]

      def retrieve_line_items: (
        String payment_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::PaymentRetrieveLineItemsResponse

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
