module Dodopayments
  module Resources
    class Payouts
      def list: (
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Models::PayoutListResponse]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
