module Dodopayments
  module Resources
    class ProductCollections
      attr_reader groups: Dodopayments::Resources::ProductCollections::Groups

      def create: (
        groups: ::Array[Dodopayments::ProductCollections::ProductCollectionGroupDetails],
        name: String,
        ?brand_id: String?,
        ?description: String?,
        ?effective_at_on_downgrade: Dodopayments::Models::ProductCollectionCreateParams::effective_at_on_downgrade?,
        ?effective_at_on_upgrade: Dodopayments::Models::ProductCollectionCreateParams::effective_at_on_upgrade?,
        ?on_payment_failure: Dodopayments::Models::ProductCollectionCreateParams::on_payment_failure?,
        ?proration_billing_mode_on_downgrade: Dodopayments::Models::ProductCollectionCreateParams::proration_billing_mode_on_downgrade?,
        ?proration_billing_mode_on_upgrade: Dodopayments::Models::ProductCollectionCreateParams::proration_billing_mode_on_upgrade?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::ProductCollection

      def retrieve: (
        String id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::ProductCollection

      def update: (
        String id,
        ?brand_id: String?,
        ?description: String?,
        ?effective_at_on_downgrade: Dodopayments::Models::ProductCollectionUpdateParams::effective_at_on_downgrade?,
        ?effective_at_on_upgrade: Dodopayments::Models::ProductCollectionUpdateParams::effective_at_on_upgrade?,
        ?group_order: ::Array[String]?,
        ?image_id: String?,
        ?name: String?,
        ?on_payment_failure: Dodopayments::Models::ProductCollectionUpdateParams::on_payment_failure?,
        ?proration_billing_mode_on_downgrade: Dodopayments::Models::ProductCollectionUpdateParams::proration_billing_mode_on_downgrade?,
        ?proration_billing_mode_on_upgrade: Dodopayments::Models::ProductCollectionUpdateParams::proration_billing_mode_on_upgrade?,
        ?request_options: Dodopayments::request_opts
      ) -> nil

      def list: (
        ?archived: bool,
        ?brand_id: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Models::ProductCollectionListResponse]

      def delete: (
        String id,
        ?request_options: Dodopayments::request_opts
      ) -> nil

      def unarchive: (
        String id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::ProductCollectionUnarchiveResponse

      def update_images: (
        String id,
        ?force_update: bool?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::ProductCollectionUpdateImagesResponse

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
