module Dodopayments
  module Resources
    class Refunds
      def create: (
        payment_id: String,
        ?reason: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::Refund

      def retrieve: (
        String refund_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::Refund

      def list: (
        ?created_at_gte: Time?,
        ?created_at_lte: Time?,
        ?customer_id: String?,
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?status: Dodopayments::Models::refund_status?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Models::Refund]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
