module Dodopayments
  module Resources
    class Webhooks
      attr_reader headers: Dodopayments::Resources::Webhooks::Headers

      def create: (
        url: String,
        ?description: String?,
        ?disabled: bool?,
        ?filter_types: ::Array[Dodopayments::Models::webhook_event_type],
        ?headers: ::Hash[Symbol, String]?,
        ?idempotency_key: String?,
        ?metadata: ::Hash[Symbol, String]?,
        ?rate_limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::WebhookDetails

      def retrieve: (
        String webhook_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::WebhookDetails

      def update: (
        String webhook_id,
        ?description: String?,
        ?disabled: bool?,
        ?filter_types: ::Array[Dodopayments::Models::webhook_event_type]?,
        ?metadata: ::Hash[Symbol, String]?,
        ?rate_limit: Integer?,
        ?url: String?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::WebhookDetails

      def list: (
        ?iterator: String?,
        ?limit: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::CursorPagePagination[Dodopayments::WebhookDetails]

      def delete: (
        String webhook_id,
        ?request_options: Dodopayments::request_opts
      ) -> nil

      def retrieve_secret: (
        String webhook_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::WebhookRetrieveSecretResponse

      def unsafe_unwrap: (
        String payload
      ) -> (Dodopayments::DisputeAcceptedWebhookEvent
      | Dodopayments::DisputeCancelledWebhookEvent
      | Dodopayments::DisputeChallengedWebhookEvent
      | Dodopayments::DisputeExpiredWebhookEvent
      | Dodopayments::DisputeLostWebhookEvent
      | Dodopayments::DisputeOpenedWebhookEvent
      | Dodopayments::DisputeWonWebhookEvent
      | Dodopayments::LicenseKeyCreatedWebhookEvent
      | Dodopayments::PaymentCancelledWebhookEvent
      | Dodopayments::PaymentFailedWebhookEvent
      | Dodopayments::PaymentProcessingWebhookEvent
      | Dodopayments::PaymentSucceededWebhookEvent
      | Dodopayments::RefundFailedWebhookEvent
      | Dodopayments::RefundSucceededWebhookEvent
      | Dodopayments::SubscriptionActiveWebhookEvent
      | Dodopayments::SubscriptionCancelledWebhookEvent
      | Dodopayments::SubscriptionExpiredWebhookEvent
      | Dodopayments::SubscriptionFailedWebhookEvent
      | Dodopayments::SubscriptionOnHoldWebhookEvent
      | Dodopayments::SubscriptionPlanChangedWebhookEvent
      | Dodopayments::SubscriptionRenewedWebhookEvent
      | Dodopayments::SubscriptionUpdatedWebhookEvent)

      def unwrap: (
        String payload
      ) -> (Dodopayments::DisputeAcceptedWebhookEvent
      | Dodopayments::DisputeCancelledWebhookEvent
      | Dodopayments::DisputeChallengedWebhookEvent
      | Dodopayments::DisputeExpiredWebhookEvent
      | Dodopayments::DisputeLostWebhookEvent
      | Dodopayments::DisputeOpenedWebhookEvent
      | Dodopayments::DisputeWonWebhookEvent
      | Dodopayments::LicenseKeyCreatedWebhookEvent
      | Dodopayments::PaymentCancelledWebhookEvent
      | Dodopayments::PaymentFailedWebhookEvent
      | Dodopayments::PaymentProcessingWebhookEvent
      | Dodopayments::PaymentSucceededWebhookEvent
      | Dodopayments::RefundFailedWebhookEvent
      | Dodopayments::RefundSucceededWebhookEvent
      | Dodopayments::SubscriptionActiveWebhookEvent
      | Dodopayments::SubscriptionCancelledWebhookEvent
      | Dodopayments::SubscriptionExpiredWebhookEvent
      | Dodopayments::SubscriptionFailedWebhookEvent
      | Dodopayments::SubscriptionOnHoldWebhookEvent
      | Dodopayments::SubscriptionPlanChangedWebhookEvent
      | Dodopayments::SubscriptionRenewedWebhookEvent
      | Dodopayments::SubscriptionUpdatedWebhookEvent)

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
