module Dodopayments
  module Resources
    class WebhookEvents
      def retrieve: (
        String webhook_event_id,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Models::WebhookEvent

      def list: (
        ?created_at_gte: Time?,
        ?created_at_lte: Time?,
        ?limit: Integer?,
        ?object_id_: String?,
        ?page_number: Integer?,
        ?page_size: Integer?,
        ?request_options: Dodopayments::request_opts
      ) -> Dodopayments::Internal::DefaultPageNumberPagination[Dodopayments::Models::WebhookEvent]

      def initialize: (client: Dodopayments::Client) -> void
    end
  end
end
