module DodoPayments
  module Resources
    class Misc
      class SupportedCountries
        def list:
          (
            ?DodoPayments::Models::Misc::SupportedCountryListParams
            | ::Hash[Symbol, top] params
          ) -> DodoPayments::Models::Misc::supported_country_list_response
          | (
            request_options: DodoPayments::request_opts
          ) -> DodoPayments::Models::Misc::supported_country_list_response

        def initialize: (client: DodoPayments::Client) -> void
      end
    end
  end
end
