module Dodopayments
  module Models
    module Payouts
      module Breakup
        type detail_list_response =
          {
            id: String,
            created_at: Time,
            event_type: String,
            original_amount: Integer,
            original_currency: String,
            payout_currency_amount: Integer,
            usd_equivalent_amount: Integer,
            description: String?,
            reference_object_id: String?
          }

        class DetailListResponse < Dodopayments::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor event_type: String

          attr_accessor original_amount: Integer

          attr_accessor original_currency: String

          attr_accessor payout_currency_amount: Integer

          attr_accessor usd_equivalent_amount: Integer

          attr_accessor description: String?

          attr_accessor reference_object_id: String?

          def initialize: (
            id: String,
            created_at: Time,
            event_type: String,
            original_amount: Integer,
            original_currency: String,
            payout_currency_amount: Integer,
            usd_equivalent_amount: Integer,
            ?description: String?,
            ?reference_object_id: String?
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Time,
            event_type: String,
            original_amount: Integer,
            original_currency: String,
            payout_currency_amount: Integer,
            usd_equivalent_amount: Integer,
            description: String?,
            reference_object_id: String?
          }
        end
      end
    end
  end
end
