module Dodopayments
  module Resources
    class Invoices
      class Payments
        def retrieve: (
          String payment_id,
          ?request_options: Dodopayments::request_opts
        ) -> StringIO

        def initialize: (client: Dodopayments::Client) -> void
      end
    end
  end
end
