module Dodopayments
  module Models
    module Payouts
      type breakup_retrieve_params =
        { payout_id: String } & Dodopayments::Internal::Type::request_parameters

      class BreakupRetrieveParams < Dodopayments::Internal::Type::BaseModel
        extend Dodopayments::Internal::Type::RequestParameters::Converter
        include Dodopayments::Internal::Type::RequestParameters

        attr_accessor payout_id: String

        def initialize: (
          payout_id: String,
          ?request_options: Dodopayments::request_opts
        ) -> void

        def to_hash: -> {
          payout_id: String,
          request_options: Dodopayments::RequestOptions
        }
      end
    end
  end
end
