module DodoPayments
  module Models
    module Customers
      module CustomerPortal
        type session_create_params =
          { send_email: bool? } & DodoPayments::request_parameters

        class SessionCreateParams < DodoPayments::BaseModel
          extend DodoPayments::RequestParameters::Converter
          include DodoPayments::RequestParameters

          attr_accessor send_email: bool?

          def initialize:
            (
              send_email: bool?,
              request_options: DodoPayments::request_opts
            ) -> void
            | (
              ?DodoPayments::Models::Customers::CustomerPortal::session_create_params
              | DodoPayments::BaseModel data
            ) -> void

          def to_hash: -> DodoPayments::Models::Customers::CustomerPortal::session_create_params
        end
      end
    end
  end
end
