module DodoPayments
  module Resources
    class Customers
      class CustomerPortal
        class Session
          def create:
            (
              String customer_id,
              ?DodoPayments::Models::Customers::CustomerPortal::SessionCreateParams
              | ::Hash[Symbol, top] params
            ) -> nil
            | (
              String customer_id,
              send_email: bool?,
              request_options: DodoPayments::request_opts
            ) -> nil

          def initialize: (client: DodoPayments::Client) -> void
        end
      end
    end
  end
end
