name: Create releases
on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am UTC
  push:
    branches:
      - main

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'dodopayments/dodopayments-ruby'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: stainless-api/trigger-release-please@v1
        id: release
        with:
          repo: ${{ github.event.repository.full_name }}
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Publish to RubyGems.org
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./bin/publish-gem
        env:
          # `RUBYGEMS_HOST` is only required for private gem repositories, not https://rubygems.org
          RUBYGEMS_HOST: ${{ secrets.DODO_PAYMENTS_RUBYGEMS_HOST || secrets.RUBYGEMS_HOST }}
          GEM_HOST_API_KEY: ${{ secrets.DODO_PAYMENTS_GEM_HOST_API_KEY || secrets.GEM_HOST_API_KEY }}

      - name: Update RubyDocs
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          curl --request POST --include --header 'Content-Type: application/json' --data '{"repository":{"url":"https://github.com/dodopayments/dodopayments-ruby"}}' -- https://www.rubydoc.info/checkout
